# Monitor-GeneratedSkills.ps1
# Tracks performance of auto-generated skills and recommends improvements/deprecation

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("Weekly", "Monthly", "All")]
    [string]$Report = "Weekly"
)

$ErrorActionPreference = "Stop"

# Paths
$LearningDB = "D:\databases\agent_learning.db"
$SkillsDir = "C:\dev\.agent\skills"

Write-Host "Auto-Generated Skills Performance Monitor" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Gray
Write-Host "Report Type: $Report" -ForegroundColor White
Write-Host ""

# Check if monitoring table exists
$checkTableQuery = @"
SELECT name FROM sqlite_master
WHERE type='table' AND name='generated_skills';
"@

$tableExists = sqlite3 $LearningDB $checkTableQuery

if (-not $tableExists) {
    Write-Host "Creating generated_skills monitoring table..." -ForegroundColor Yellow

    $createTableQuery = @"
CREATE TABLE IF NOT EXISTS generated_skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    success_rate REAL DEFAULT 0,
    usage_count INTEGER DEFAULT 0,
    user_rating INTEGER,
    deprecation_candidate BOOLEAN DEFAULT 0,
    last_used TIMESTAMP,
    notes TEXT
);
"@

    sqlite3 $LearningDB $createTableQuery
    Write-Host "Table created successfully" -ForegroundColor Green
    Write-Host ""
}

# Get all auto-generated skills
$skills = Get-ChildItem -Path $SkillsDir -Directory | ForEach-Object {
    $skillMd = Join-Path $_.FullName "SKILL.md"
    if (Test-Path $skillMd) {
        $content = Get-Content $skillMd -Raw
        if ($content -match 'generated_from:|Auto-generated') {
            [PSCustomObject]@{
                Name = $_.Name
                Path = $skillMd
                AutoGenerated = $true
            }
        }
    }
}

if ($skills.Count -eq 0) {
    Write-Host "No auto-generated skills found yet." -ForegroundColor Yellow
    Write-Host "Generate your first skill with: .\Generate-Skill.ps1 -PatternName <name>" -ForegroundColor Gray
    exit 0
}

Write-Host "Found $($skills.Count) auto-generated skills" -ForegroundColor Green
Write-Host ""

# Get performance metrics
$timeFilter = switch ($Report) {
    "Weekly" { "datetime('now', '-7 days')" }
    "Monthly" { "datetime('now', '-30 days')" }
    "All" { "'1970-01-01'" }
}

$performanceQuery = @"
SELECT
    gs.name,
    gs.type,
    gs.success_rate,
    gs.usage_count,
    gs.user_rating,
    gs.deprecation_candidate,
    gs.generated_at,
    gs.last_used,
    COUNT(ae.id) as recent_uses
FROM generated_skills gs
LEFT JOIN agent_executions ae ON (
    ae.tools_used LIKE '%' || gs.name || '%'
    OR ae.task_type = gs.name
)
    AND ae.executed_at >= $timeFilter
GROUP BY gs.name, gs.type, gs.success_rate, gs.usage_count, gs.user_rating, gs.deprecation_candidate, gs.generated_at, gs.last_used
ORDER BY gs.usage_count DESC, gs.success_rate DESC;
"@

$metricsRaw = sqlite3 -header -separator '|' $LearningDB $performanceQuery
if ($metricsRaw) {
    $metrics = $metricsRaw | ConvertFrom-Csv -Delimiter '|'
} else {
    $metrics = @()
}

if ($metrics.Count -eq 0) {
    Write-Host "No performance data yet." -ForegroundColor Yellow
    Write-Host "Skills will be tracked as they are used." -ForegroundColor Gray

    # Register skills in database
    foreach ($skill in $skills) {
        $insertQuery = @"
INSERT OR IGNORE INTO generated_skills (name, type)
VALUES ('$($skill.Name)', 'skill');
"@
        sqlite3 $LearningDB $insertQuery
    }

    Write-Host ""
    Write-Host "Skills registered for monitoring: $($skills.Count)" -ForegroundColor Green
    exit 0
}

# Display performance report
Write-Host "Performance Report ($Report)" -ForegroundColor Cyan
Write-Host "=============================" -ForegroundColor Gray
Write-Host ""

$metrics | Format-Table -Property @(
    @{Label="Skill"; Expression={$_.name}; Width=30},
    @{Label="Uses"; Expression={$_.usage_count}; Width=8},
    @{Label="Success %"; Expression={[Math]::Round($_.success_rate * 100, 1)}; Width=10},
    @{Label="Rating"; Expression={if($_.user_rating){$_.user_rating}else{"-"}}; Width=8},
    @{Label="Last Used"; Expression={if($_.last_used){$_.last_used.Substring(0,10)}else{"-"}}; Width=12}
) -AutoSize

Write-Host ""

# Identify high performers
$highPerformers = $metrics | Where-Object {
    $_.usage_count -ge 20 -and [double]$_.success_rate -ge 0.85
}

if ($highPerformers.Count -gt 0) {
    Write-Host "🌟 High Performers (>20 uses, >85% success):" -ForegroundColor Green
    $highPerformers | ForEach-Object {
        Write-Host "  • $($_.name) - $($_.usage_count) uses, $([Math]::Round($_.success_rate * 100, 1))% success" -ForegroundColor Green
    }
    Write-Host ""
}

# Identify medium performers
$mediumPerformers = $metrics | Where-Object {
    [double]$_.success_rate -ge 0.60 -and [double]$_.success_rate -lt 0.85
}

if ($mediumPerformers.Count -gt 0) {
    Write-Host "⚡ Medium Performers (60-85% success):" -ForegroundColor Yellow
    $mediumPerformers | ForEach-Object {
        Write-Host "  • $($_.name) - Needs improvement" -ForegroundColor Yellow
    }
    Write-Host ""
}

# Identify deprecation candidates
$deprecationCandidates = $metrics | Where-Object {
    $_.usage_count -ge 20 -and [double]$_.success_rate -lt 0.60
}

if ($deprecationCandidates.Count -gt 0) {
    Write-Host "❌ Deprecation Candidates (<60% success after 20+ uses):" -ForegroundColor Red
    $deprecationCandidates | ForEach-Object {
        Write-Host "  • $($_.name) - Consider deprecating or rewriting" -ForegroundColor Red

        # Mark as deprecation candidate
        $updateQuery = @"
UPDATE generated_skills
SET deprecation_candidate = 1
WHERE name = '$($_.name)';
"@
        sqlite3 $LearningDB $updateQuery
    }
    Write-Host ""
}

# Identify unused skills
$unusedSkills = $metrics | Where-Object { $_.usage_count -eq 0 }

if ($unusedSkills.Count -gt 0) {
    Write-Host "💤 Unused Skills (0 uses):" -ForegroundColor Gray
    $unusedSkills | ForEach-Object {
        $daysSinceGeneration = ((Get-Date) - [DateTime]$_.generated_at).Days
        Write-Host "  • $($_.name) - Generated $daysSinceGeneration days ago" -ForegroundColor Gray
    }
    Write-Host ""
}

# Summary statistics
$avgSuccessRate = ($metrics | Measure-Object -Property success_rate -Average).Average
$totalUses = ($metrics | Measure-Object -Property usage_count -Sum).Sum

Write-Host "Summary Statistics:" -ForegroundColor Cyan
Write-Host "  Total Auto-Generated Skills: $($metrics.Count)" -ForegroundColor White
Write-Host "  Average Success Rate: $([Math]::Round($avgSuccessRate * 100, 1))%" -ForegroundColor White
Write-Host "  Total Uses: $totalUses" -ForegroundColor White
Write-Host "  High Performers: $($highPerformers.Count)" -ForegroundColor Green
Write-Host "  Medium Performers: $($mediumPerformers.Count)" -ForegroundColor Yellow
Write-Host "  Deprecation Candidates: $($deprecationCandidates.Count)" -ForegroundColor Red
Write-Host "  Unused: $($unusedSkills.Count)" -ForegroundColor Gray
Write-Host ""

# Recommendations
Write-Host "Recommendations:" -ForegroundColor Cyan
Write-Host "================" -ForegroundColor Gray

if ($deprecationCandidates.Count -gt 0) {
    Write-Host "1. Review deprecation candidates for failures:" -ForegroundColor Yellow
    $deprecationCandidates | ForEach-Object {
        Write-Host "   - Analyze errors for: $($_.name)" -ForegroundColor White
        Write-Host "     Query: SELECT error_details FROM agent_executions WHERE tools_used LIKE '%$($_.name)%' AND status='failed' LIMIT 10;" -ForegroundColor Gray
    }
    Write-Host ""
}

if ($unusedSkills.Count -gt 0) {
    Write-Host "2. Consider removing unused skills after 60 days:" -ForegroundColor Yellow
    $unusedSkills | Where-Object {
        ((Get-Date) - [DateTime]$_.generated_at).Days -gt 60
    } | ForEach-Object {
        Write-Host "   - Remove: $($_.name)" -ForegroundColor Gray
    }
    Write-Host ""
}

if ($highPerformers.Count -gt 0) {
    Write-Host "3. Promote high performers:" -ForegroundColor Green
    Write-Host "   - Document success patterns" -ForegroundColor White
    Write-Host "   - Use as templates for new skill generation" -ForegroundColor White
    Write-Host "   - Consider creating variations (A/B testing)" -ForegroundColor White
    Write-Host ""
}

Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  - Run weekly: .\Monitor-GeneratedSkills.ps1 -Report Weekly" -ForegroundColor White
Write-Host "  - Run monthly: .\Monitor-GeneratedSkills.ps1 -Report Monthly" -ForegroundColor White
Write-Host "  - Check all time: .\Monitor-GeneratedSkills.ps1 -Report All" -ForegroundColor White
