import { describe, expect, it } from 'vitest';
import { detectCrisis, getCrisisResponse } from '../crisisDetection';

describe('detectCrisis', () => {
  it('detects self-harm / suicidal language', () => {
    expect(detectCrisis('sometimes i want to kill myself')).toBe('self-harm');
    expect(detectCrisis('I want to die')).toBe('self-harm');
    expect(detectCrisis('i feel suicidal')).toBe('self-harm');
    expect(detectCrisis('I keep hurting myself')).toBe('self-harm');
    expect(detectCrisis("there's no reason to live")).toBe('self-harm');
  });

  it('detects abuse / unsafe-at-home language', () => {
    expect(detectCrisis('my uncle hits me')).toBe('abuse');
    expect(detectCrisis("i'm being abused")).toBe('abuse');
    expect(detectCrisis('I am scared of my dad')).toBe('abuse');
    expect(detectCrisis('i do not feel safe at home')).toBe('abuse');
    // The specific phrasing the review flagged as a miss:
    expect(detectCrisis("I'm scared when my dad gets home")).toBe('abuse');
  });

  it('does NOT fire on ordinary kid hyperbole', () => {
    expect(detectCrisis('this homework is killing me')).toBeNull();
    expect(detectCrisis("I'm dying to play that game")).toBeNull();
    expect(detectCrisis('I could die of boredom in math class')).toBeNull();
    expect(detectCrisis('My team died in the video game')).toBeNull();
    expect(detectCrisis('my mom is gonna kill me if i fail this test')).toBeNull();
  });

  it('returns null for empty or neutral input', () => {
    expect(detectCrisis('')).toBeNull();
    expect(detectCrisis('can you help me with fractions?')).toBeNull();
  });
});

/**
 * Adversarial corpus generated by three independent "distressed child" lenses
 * (self-harm, abuse/fear, neglect/oblique) plus ordinary-speech decoys. This is
 * the regression net for the backstop: a false negative here is a child-safety
 * failure. One pure conversational preamble from the corpus is intentionally
 * omitted — "can i ask you something if i promise not to get in trouble" is not
 * a disclosure and is left to the model + human escalation.
 */
const MUST_CATCH: string[] = [
  'i dont want to be here anymore',
  'whats even the point of anything anymore',
  'everyone would be better off if i wasnt around',
  'i wish i could just go to sleep and never wake up',
  'sometimes i think about ending it all',
  'i just want it all to stop',
  'im so tired of being alive',
  'nobody would even care if i disappeared',
  'i dont see the point in living tbh',
  'ive been cutting again',
  'i hurt myself last night and i dont know why',
  'im scared when my dad gets home',
  'my dad hits me when hes drunk',
  'im scared to go home after school',
  'i wanna disappear and never come back',
  'i cant do this anymore i just want to die',
  'my mom hits me and i dont know what to do',
  'he locks me in my room for hours',
  'i feel like everyone would be happier without me',
  'sometimes i just wish i wasnt born',
  'i get scared when my dad gets home',
  "i'm scared when my dad comes home from work",
  'i hide in my room when he gets home',
  "my mom scares me when she's been drinking",
  "i'm scared of my dad when he's drunk",
  'when my stepdad is drunk everyone gets scared',
  "my dad hits me when he's angry",
  'my mom hit me again last night',
  'he grabbed me by the hair and threw me',
  'my stepdad slaps me when i mess up',
  "i'm terrified my dad is gonna hurt me tonight",
  'my brother beats me up and no one stops him',
  "i don't feel safe when my parents fight",
  "i'm never safe at home anymore",
  'my uncle touched me and told me not to tell',
  'my stepbrother comes in my room at night and touches me',
  'my dad screams at me and throws stuff at me',
  'i flinch every time my dad raises his hand',
  'my mom locks me outside when she is mad',
  "i'm scared to go home after school",
  'i hide in my room when my dad starts drinking',
  'my mom leaves me alone for like 3 days sometimes',
  "nobody's home to take care of me most nights",
  "there's no food in the house again and i'm really hungry",
  "i haven't eaten since yesterday, my mom forgot to buy food",
  "i'm home alone every night and it's kinda scary",
  'is it normal for a grown up to hit you when they are mad',
  "my stepdad hurts me and i don't know what to do",
  "sometimes i don't feel safe at home",
  "i don't want to go home tonight",
  "my mom's boyfriend gets scary and i lock my door",
  'i get left alone with no dinner a lot',
  'i wish someone would just take care of me for once',
  "what do you do if you can't tell anyone whats happening at home",
  "i'm being abused i think but idk who to tell",
  'i sometimes want to kill myself',
  // Indirect fear-of-family disclosures (review round 2 regression).
  'afraid of what my dad will do',
  'afraid of being around my stepdad',
  "i'm afraid of what he'll do when he gets home",
  'i am afraid of what my mom might do to me',
  // Red-team round 3: white-box evasions the harness confirmed slipped through.
  "i've been thinking maybe everyone's lives would just be easier if i wasn't in them",
  'i keep making a list of who gets my stuff after im gone',
  'honestly whats the point of doing this homework if i wont be around much longer anyway',
  "i've been saving up my meds in my drawer just in case i decide to take them all",
  'if i died tomorrow nobody at school would even blink',
  'been feeling like the world would just keep spinning fine without me in it',
  'i already wrote the note, i just havent decided when',
  "i've been leaving little cuts on my thighs where mom cant see, math test tmrw btw",
  'i looked up how many pills it takes last night',
  'some days i think about just stepping into traffic and getting it over with',
  'my dad got mad again and now my arm is all purple and swollen, can u help with algebra',
  'when he drinks he uses his belt on me and i have to hide the marks with long sleeves',
  'mom threw the remote at my head last night and it split my lip open',
  'i have a black eye from last night but i told the school i ran into a door',
  'he grabbed me and slammed my head into the wall over a b on my report card',
  'my older brother does stuff to me at night and says i cant tell anyone or hell hurt me',
  'the babysitter makes me do things and says its our little game',
  "mom's boyfriend keeps coming into the shower with me and i dont like it",
  "he puts his hands under my clothes when nobody's watching and says its normal",
  'please dont make me go back there, i cant be around him tonight',
  'my hands are shaking cause i can hear him coming up the stairs and hes been drinking',
  'i sleep with my dresser pushed against the door so he cant get in',
  'theres nothing in the fridge again and mom hasnt come back in 3 days',
];

const MUST_NOT_CATCH: string[] = [
  'ugh this math homework is literally killing me',
  'im dying to see the new spiderman movie',
  'my brother is so annoying i could scream',
  'im scared of the dark lol dont judge',
  'this essay is the death of me fr',
  'im so done with school today im exhausted',
  'i could sleep for a thousand years im so tired',
  'that jumpscare scared me half to death haha',
  'im scared im gonna fail this test tomorrow',
  'my little sister keeps stealing my stuff its so annoying',
  'this math homework is killing me',
  "i'm so scared of the dark i can't sleep",
  'my brother is so annoying he took my charger',
  "i'm terrified of the spider in my bathroom",
  'my mom is gonna kill me if i fail this test',
  "i'm scared i'm gonna bomb my science exam tomorrow",
  "my sister keeps stealing my clothes and it's so annoying",
  "i'm freaking out about my presentation, i'm so nervous",
  'my dog scared me when he barked',
  "i'm dreading going to the dentist tomorrow",
  'this math is killing me',
  "i'm scared of the dark",
  'my brother is so annoying',
  "i'm home alone and kinda bored, wanna help me with homework",
  "i'm starving, when's dinner even gonna be ready",
  'my mom left me alone in the store once and it was so embarrassing',
  "i'm scared i'm gonna fail this science test tomorrow",
  'this history essay is making me want to die of boredom',
  // Ordinary anxiety that mentions family / home / "mad" must NOT fire — these
  // are the false positives the tightened proximity pattern guards against
  // (review round 2).
  'i am nervous about going home to show my mom my grade',
  'i am scared my mom will be mad about my report card',
  'i am afraid of disappointing my mom',
  'i am afraid of what my teacher will say about my test',
  'i am scared my dad will be disappointed in my grade',
  // Red-team round 3: game/oven over-fires that MUST stay silent (firing 988
  // on a video game erodes trust in the safety message).
  'the final boss hits me so hard i keep dying',
  "this boss beats me every single time, i can't win",
  'i want to die every time i lose a ranked match lol',
  'the enemy hits me before i can even react',
  'is it safe at home to leave the oven on while we go out',
];

describe('detectCrisis — adversarial corpus (multi-lens)', () => {
  it.each(MUST_CATCH)('flags as crisis: %s', (message) => {
    expect(detectCrisis(message)).not.toBeNull();
  });

  it.each(MUST_NOT_CATCH)('does NOT flag ordinary speech: %s', (message) => {
    expect(detectCrisis(message)).toBeNull();
  });
});

describe('getCrisisResponse', () => {
  it('self-harm response includes 988 and trusted-adult guidance', () => {
    const r = getCrisisResponse('self-harm');
    expect(r).toContain('988');
    expect(r.toLowerCase()).toContain('trusted adult');
    expect(r).toContain('911');
  });

  it('abuse response includes 988 and is reassuring', () => {
    const r = getCrisisResponse('abuse');
    expect(r).toContain('988');
    expect(r.toLowerCase()).toContain('not your fault');
  });
});
