import { useCallback, useEffect, useMemo, useState } from 'react';
import { LandingPage, createDefaultLandingContent } from '@vibetech/landing';

const content = createDefaultLandingContent({
  productName: 'CME Track',
  badge: 'Generated by @vibetech/factory:saas',
  title: 'Continuing Education Credit Tracker',
  subtitle:
    'Track CME credits, monitor certification targets, and secure your logs under CME Track Pro.',
  previewItems: [
    'Log CME Activity',
    'Calculate total hours',
    'Track progress to target',
    'Export credits list',
  ],
  featuresHeading: 'Core tracking features',
  featuresSubheading:
    'Track CME Category 1/2 requirements and monitor remaining hours required to renew your professional license.',
  features: [
    {
      title: 'Activity log',
      description: 'Log title, credit hours, category, date, and provider in one secure vault.',
    },
    {
      title: 'Target monitoring',
      description: 'Visual progress meters tracking completion against standard 50-hour goals.',
    },
    {
      title: 'Secure entitlement',
      description: 'Logs and stats safely gated under the secure CME Track Pro SQLite data layer.',
    },
  ],
  ctaHeading: 'Start tracking CME requirements today',
  ctaBody:
    'Subscribe to CME Track Pro to get unlimited logging and visual target tracking.',
  footerRight: 'Built with the VibeTech factory SaaS generator',
});

interface GeneratedAuthUser {
  email: string;
  fullName?: string;
}

interface CmeActivity {
  id: number;
  user_email: string;
  title: string;
  hours: number;
  category: string;
  date_earned: string;
  provider: string;
}

export function App() {
  const pathname = window.location.pathname;
  const [authConfigured, setAuthConfigured] = useState(false);
  const [userEmail, setUserEmail] = useState('');
  const [password, setPassword] = useState('');
  const [currentUser, setCurrentUser] = useState<GeneratedAuthUser | null>(null);
  const [currentPlan, setCurrentPlan] = useState<string>('free');
  const [authMessage, setAuthMessage] = useState<string | null>(null);
  const [proMessage, setProMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState<'auth' | 'pro' | 'cme' | null>(null);
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [checkoutError, setCheckoutError] = useState<string | null>(null);
  
  // CME Activity list and form state
  const [activities, setActivities] = useState<CmeActivity[]>([]);
  const [formTitle, setFormTitle] = useState('');
  const [formHours, setFormHours] = useState('');
  const [formCategory, setFormCategory] = useState('Category 1 AMA');
  const [formDate, setFormDate] = useState('');
  const [formProvider, setFormProvider] = useState('');
  const [formMessage, setFormMessage] = useState<string | null>(null);

  const apiBase = useMemo(() => import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:5360', []);

  const fetchCmeLogs = useCallback(async () => {
    try {
      const response = await fetch(`${apiBase}/api/cme`, {
        credentials: 'include',
      });
      const body = await response.json();
      if (response.ok && Array.isArray(body.activities)) {
        setActivities(body.activities);
      }
    } catch {
      // Quietly ignore failed logs query (e.g. if unauthenticated or free)
    }
  }, [apiBase]);

  const refreshSession = useCallback(async () => {
    try {
      const response = await fetch(`${apiBase}/api/auth/me`, {
        credentials: 'include',
      });
      const body = (await response.json()) as {
        configured?: boolean;
        user?: GeneratedAuthUser | null;
      };

      setAuthConfigured(Boolean(body.configured));
      setCurrentUser(body.user ?? null);
      
      if (body.user) {
        // Fetch current plan status
        const proRes = await fetch(`${apiBase}/api/pro`, {
          credentials: 'include',
        });
        const proBody = await proRes.json();
        if (proRes.ok) {
          setCurrentPlan(proBody.plan || 'pro');
          await fetchCmeLogs();
        } else {
          setCurrentPlan(proBody.plan || 'free');
        }
      } else {
        setCurrentPlan('free');
        setActivities([]);
      }
    } catch {
      setAuthConfigured(false);
      setCurrentUser(null);
      setCurrentPlan('free');
      setActivities([]);
    }
  }, [apiBase, fetchCmeLogs]);

  useEffect(() => {
    void refreshSession();
  }, [refreshSession]);

  async function signIn() {
    setLoading('auth');
    setAuthMessage(null);

    try {
      const response = await fetch(`${apiBase}/api/auth/login`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          email: userEmail,
          password,
        }),
      });
      const body = (await response.json()) as {
        user?: GeneratedAuthUser;
        error?: string;
        detail?: string;
      };

      if (!response.ok || !body.user) {
        throw new Error(body.detail ?? body.error ?? 'Unable to sign in');
      }

      setCurrentUser(body.user);
      setAuthConfigured(true);
      setPassword('');
      await refreshSession();
    } catch (requestError) {
      setAuthMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function signOut() {
    setLoading('auth');
    setAuthMessage(null);

    try {
      await fetch(`${apiBase}/api/auth/logout`, {
        method: 'POST',
        credentials: 'include',
      });
      setCurrentUser(null);
      await refreshSession();
    } catch (requestError) {
      setAuthMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function checkProRoute() {
    setLoading('pro');
    setProMessage(null);

    try {
      const response = await fetch(`${apiBase}/api/pro`, {
        credentials: 'include',
      });
      const body = (await response.json()) as {
        error?: string;
        feature?: string;
        plan?: string;
      };

      if (!response.ok || !body.feature) {
        throw new Error(body.error ?? 'Protected route check failed');
      }

      setProMessage(`Protected route is live for the ${body.plan} plan: ${body.feature}.`);
    } catch (requestError) {
      setProMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function startCheckout() {
    setCheckoutLoading(true);
    setCheckoutError(null);
    try {
      const response = await fetch(`${apiBase}/api/billing/demo-checkout`, {
        method: 'GET',
        credentials: 'include',
      });
      const body = await response.json();
      if (!response.ok || !body.url) {
        throw new Error(body.error ?? body.detail ?? 'Failed to generate checkout session');
      }
      window.location.href = body.url;
    } catch (err) {
      setCheckoutError(err instanceof Error ? err.message : String(err));
    } finally {
      setCheckoutLoading(false);
    }
  }

  async function logCme(event: React.FormEvent) {
    event.preventDefault();
    setFormMessage(null);
    setLoading('cme');

    const hours = parseFloat(formHours);
    if (isNaN(hours) || hours <= 0) {
      setFormMessage('Hours must be a valid number greater than 0');
      setLoading(null);
      return;
    }

    try {
      const response = await fetch(`${apiBase}/api/cme`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          title: formTitle,
          hours,
          category: formCategory,
          date_earned: formDate,
          provider: formProvider,
        }),
      });

      if (!response.ok) {
        const body = await response.json();
        throw new Error(body.error ?? 'Failed to log CME activity');
      }

      setFormTitle('');
      setFormHours('');
      setFormCategory('Category 1 AMA');
      setFormDate('');
      setFormProvider('');
      await fetchCmeLogs();
      setFormMessage('Activity logged successfully!');
    } catch (err) {
      setFormMessage(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(null);
    }
  }

  async function deleteCme(id: number) {
    setFormMessage(null);
    try {
      const response = await fetch(`${apiBase}/api/cme/${id}`, {
        method: 'DELETE',
        credentials: 'include',
      });

      if (!response.ok) {
        const body = await response.json();
        throw new Error(body.error ?? 'Failed to delete CME activity');
      }

      await fetchCmeLogs();
      setFormMessage('Activity deleted successfully.');
    } catch (err) {
      setFormMessage(err instanceof Error ? err.message : String(err));
    }
  }

  const totalHours = useMemo(() => {
    return activities.reduce((sum, act) => sum + act.hours, 0);
  }, [activities]);

  const targetHours = 50;
  const progressPercent = Math.min(100, Math.round((totalHours / targetHours) * 100));

  if (pathname === '/billing/success') {
    return (
      <main
        style={{
          minHeight: '100vh',
          padding: '48px 24px',
          background: '#08111f',
          color: '#f5f7fb',
          fontFamily: 'Inter, system-ui, sans-serif',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <div
          style={{
            maxWidth: '500px',
            width: '100%',
            border: '1px solid rgba(148, 163, 184, 0.2)',
            borderRadius: '8px',
            background: 'rgba(15, 23, 42, 0.82)',
            padding: '32px',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>🎉</div>
          <h1 style={{ margin: '0 0 16px', fontSize: '32px' }}>Upgrade Successful!</h1>
          <p style={{ margin: '0 0 24px', color: '#b7c3d6', lineHeight: 1.6 }}>
            Thank you for upgrading to CME Track Pro. Your credit logging and visual target trackers are now fully active!
          </p>
          <button onClick={() => { window.location.href = '/'; }} style={{ width: '100%' }}>
            Go to Dashboard
          </button>
        </div>
      </main>
    );
  }

  if (pathname === '/billing/canceled') {
    return (
      <main
        style={{
          minHeight: '100vh',
          padding: '48px 24px',
          background: '#08111f',
          color: '#f5f7fb',
          fontFamily: 'Inter, system-ui, sans-serif',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <div
          style={{
            maxWidth: '500px',
            width: '100%',
            border: '1px solid rgba(148, 163, 184, 0.2)',
            borderRadius: '8px',
            background: 'rgba(15, 23, 42, 0.82)',
            padding: '32px',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>❌</div>
          <h1 style={{ margin: '0 0 16px', fontSize: '32px' }}>Checkout Canceled</h1>
          <p style={{ margin: '0 0 24px', color: '#b7c3d6', lineHeight: 1.6 }}>
            The checkout session was canceled. No charges were made.
          </p>
          <button
            onClick={() => { window.location.href = '/'; }}
            className="secondary-button"
            style={{ width: '100%' }}
          >
            Return to Dashboard
          </button>
        </div>
      </main>
    );
  }

  if (pathname === '/terms') {
    return (
      <LegalPage
        title="Terms of service"
        intro="This SaaS app includes terms of service for CME Track client portal."
        sections={[
          {
            heading: 'Use of the service',
            body: 'Use the CME Track portal to log your credit hours, track target progress, and manage certification audits.',
          },
          {
            heading: 'Billing',
            body: 'CME tracking logs are gated behind the $9/mo Pro tier subscription, powered by Stripe billing integrations.',
          },
          {
            heading: 'Acceptable use',
            body: 'Do not upload incorrect or fraudulent certification logs to the CME Track database.',
          },
        ]}
      />
    );
  }

  if (pathname === '/privacy') {
    return (
      <LegalPage
        title="Privacy policy"
        intro="This privacy policy details how CME Track handles credit logs and account data."
        sections={[
          {
            heading: 'Data collection',
            body: 'We collect your email, logged CME credits, hours, category information, and provider details.',
          },
          {
            heading: 'Payments',
            body: 'Checkout details and subscription cycles are securely processed through Stripe. Card data never touches our servers.',
          },
          {
            heading: 'Data retention',
            body: 'CME credit logs are retained for auditing purposes and are deleted only upon user request.',
          },
        ]}
      />
    );
  }

  return (
    <main>
      <LandingPage content={content} />
      <section className="page auth-grid">
        <article className="grid-card">
          <div className="eyebrow">Generated auth</div>
          <h2>
            {currentUser
              ? 'Signed in'
              : authConfigured
                ? 'Sign in required'
                : 'Auth not configured'}
          </h2>
          <p>
            {currentUser
              ? `Session active for ${currentUser.fullName ?? currentUser.email}.`
              : authConfigured
                ? 'Use the generated operator account to unlock the CME credits dashboard.'
                : 'Set AUTH_SECRET and the DEMO_USER_* values in .env before using the starter login flow.'}
          </p>
          {authMessage ? <p className="message">{authMessage}</p> : null}
        </article>
        <article className="grid-card auth-form-card">
          <div className="eyebrow">Operator account</div>
          {currentUser ? (
            <button
              className="secondary-button"
              onClick={() => void signOut()}
              disabled={loading !== null}
            >
              {loading === 'auth' ? 'Signing out...' : 'Sign out'}
            </button>
          ) : (
            <>
              <label className="field">
                Email
                <input
                  type="email"
                  value={userEmail}
                  onChange={(event) => setUserEmail(event.target.value)}
                  placeholder="owner@example.com"
                />
              </label>
              <label className="field">
                Password
                <input
                  type="password"
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                  placeholder="change-this-password"
                />
              </label>
              <button onClick={() => void signIn()} disabled={loading !== null}>
                {loading === 'auth' ? 'Signing in...' : 'Sign in for pro access'}
              </button>
            </>
          )}
        </article>
        <article className="grid-card">
          <div className="eyebrow">Pro route</div>
          <h2>/api/pro</h2>
          <p>
            The CME Track scaffold includes a secure entitlement endpoint.
          </p>
          <button
            className="secondary-button"
            onClick={() => void checkProRoute()}
            disabled={loading !== null}
          >
            {loading === 'pro' ? 'Checking route...' : 'Check protected pro route'}
          </button>
          {proMessage ? (
            <div style={{ marginTop: '12px' }}>
              <p
                className="message"
                style={{
                  color: proMessage.toLowerCase().includes('upgrade') ? '#f59e0b' : '#22d3ee',
                  fontSize: '15px'
                }}
              >
                {proMessage}
              </p>
              {proMessage.toLowerCase().includes('upgrade') && currentPlan === 'free' ? (
                <button
                  onClick={() => void startCheckout()}
                  disabled={checkoutLoading}
                  style={{ marginTop: '12px', width: '100%' }}
                >
                  {checkoutLoading ? 'Redirecting...' : 'Upgrade Now ($9/mo)'}
                </button>
              ) : null}
            </div>
          ) : null}
        </article>
        {currentUser ? (
          <article className="grid-card">
            <div className="eyebrow">Subscription & Billing</div>
            <h2>
              Plan: <span style={{ color: currentPlan === 'pro' ? '#10b981' : '#f59e0b', textTransform: 'uppercase' }}>{currentPlan}</span>
            </h2>
            <p>
              {currentPlan === 'pro'
                ? 'Thank you for upgrading! You have unlocked unlimited credit log access and progress trackers.'
                : 'Upgrade to CME Track Pro ($9/mo) to unlock logging forms and visual credit status meters.'}
            </p>
            {currentPlan === 'free' ? (
              <button
                onClick={() => void startCheckout()}
                disabled={checkoutLoading}
                style={{ width: '100%', marginTop: '8px' }}
              >
                {checkoutLoading ? 'Redirecting to Stripe...' : 'Upgrade to Pro ($9/mo)'}
              </button>
            ) : (
              <div style={{ color: '#10b981', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px', marginTop: '12px' }}>
                ✓ Pro features activated
              </div>
            )}
            {checkoutError ? (
              <p className="message" style={{ color: '#ef4444', marginTop: '8px' }}>
                {checkoutError}
              </p>
            ) : null}
          </article>
        ) : null}
      </section>

      {currentUser ? (
        <section className="page" style={{ paddingTop: '24px' }}>
          {currentPlan !== 'pro' ? (
            <article className="grid-card" style={{ textAlign: 'center', padding: '40px' }}>
              <div style={{ fontSize: '32px', marginBottom: '16px' }}>🔒</div>
              <h2>CME Dashboard Gated</h2>
              <p style={{ maxWidth: '600px', margin: '0 auto 24px' }}>
                Credit logs, tracking forms, and progress metrics are only available on the CME Track Pro tier.
              </p>
              <button onClick={() => void startCheckout()} disabled={checkoutLoading}>
                {checkoutLoading ? 'Redirecting...' : 'Unlock Pro Tier for $9/mo'}
              </button>
            </article>
          ) : (
            <div style={{ display: 'grid', gap: '24px' }}>
              <article className="grid-card">
                <div className="eyebrow">CME Progress Tracker</div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '8px' }}>
                  <h2>{totalHours} / {targetHours} Credit Hours Earned</h2>
                  <span style={{ color: progressPercent >= 100 ? '#10b981' : '#b9c6d9', fontWeight: 600 }}>
                    {progressPercent}% Complete
                  </span>
                </div>
                <div style={{ width: '100%', height: '12px', background: 'rgba(148, 163, 184, 0.2)', borderRadius: '999px', overflow: 'hidden' }}>
                  <div style={{ width: `${progressPercent}%`, height: '100%', background: '#22d3ee', transition: 'width 0.4s ease' }} />
                </div>
                <p style={{ marginTop: '12px', fontSize: '15px' }}>
                  {progressPercent >= 100 
                    ? '🎉 Congratulations! You have fully satisfied your Continuing Education target!'
                    : `You need ${Math.max(0, targetHours - totalHours)} more credit hours to reach your goal.`}
                </p>
              </article>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '24px' }}>
                <article className="grid-card">
                  <div className="eyebrow">Log CME Activity</div>
                  <form onSubmit={(e) => void logCme(e)} style={{ display: 'grid', gap: '12px' }}>
                    <label className="field">
                      Activity Title
                      <input 
                        type="text" 
                        required 
                        value={formTitle}
                        onChange={(e) => setFormTitle(e.target.value)} 
                        placeholder="e.g. Cardiopulmonary Resuscitation Course" 
                      />
                    </label>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                      <label className="field">
                        Hours
                        <input 
                          type="number" 
                          step="0.1" 
                          required 
                          value={formHours}
                          onChange={(e) => setFormHours(e.target.value)} 
                          placeholder="e.g. 4.5" 
                        />
                      </label>
                      <label className="field">
                        Category
                        <select 
                          value={formCategory} 
                          onChange={(e) => setFormCategory(e.target.value)}
                          style={{
                            width: '100%',
                            border: '1px solid rgba(148, 163, 184, 0.24)',
                            borderRadius: '6px',
                            background: 'rgba(2, 6, 23, 0.5)',
                            color: '#f8fafc',
                            padding: '10px 12px',
                            minHeight: '42px'
                          }}
                        >
                          <option value="Category 1 AMA">Category 1 AMA</option>
                          <option value="Category 2">Category 2</option>
                          <option value="Other / General">Other / General</option>
                        </select>
                      </label>
                    </div>
                    <label className="field">
                      Date Earned
                      <input 
                        type="date" 
                        required 
                        value={formDate}
                        onChange={(e) => setFormDate(e.target.value)} 
                      />
                    </label>
                    <label className="field">
                      Provider
                      <input 
                        type="text" 
                        required 
                        value={formProvider}
                        onChange={(e) => setFormProvider(e.target.value)} 
                        placeholder="e.g. American Heart Association" 
                      />
                    </label>
                    <button type="submit" disabled={loading === 'cme'} style={{ width: '100%', marginTop: '8px' }}>
                      {loading === 'cme' ? 'Logging Credit...' : 'Log Credit'}
                    </button>
                    {formMessage ? (
                      <p className="message" style={{ color: formMessage.includes('successfully') ? '#10b981' : '#ef4444', fontSize: '14px', marginTop: '4px' }}>
                        {formMessage}
                      </p>
                    ) : null}
                  </form>
                </article>

                <article className="grid-card" style={{ display: 'grid', alignContent: 'start', overflowX: 'auto' }}>
                  <div className="eyebrow">Logged Credits</div>
                  {activities.length === 0 ? (
                    <p style={{ color: '#b9c6d9', margin: '20px 0' }}>No CME credit hours logged yet. Use the form to log your first activity.</p>
                  ) : (
                    <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '12px' }}>
                      <thead>
                        <tr style={{ borderBottom: '1px solid rgba(148, 163, 184, 0.24)', textAlign: 'left' }}>
                          <th style={{ padding: '10px' }}>Activity</th>
                          <th style={{ padding: '10px' }}>Category</th>
                          <th style={{ padding: '10px' }}>Hours</th>
                          <th style={{ padding: '10px' }}>Date</th>
                          <th style={{ padding: '10px' }}>Provider</th>
                          <th style={{ padding: '10px', textAlign: 'center' }}>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {activities.map((act) => (
                          <tr key={act.id} style={{ borderBottom: '1px solid rgba(148, 163, 184, 0.12)' }}>
                            <td style={{ padding: '10px', fontWeight: 500 }}>{act.title}</td>
                            <td style={{ padding: '10px', color: '#b9c6d9' }}>{act.category}</td>
                            <td style={{ padding: '10px', fontWeight: 600, color: '#22d3ee' }}>{act.hours}</td>
                            <td style={{ padding: '10px', color: '#b9c6d9' }}>{act.date_earned}</td>
                            <td style={{ padding: '10px', color: '#b9c6d9' }}>{act.provider}</td>
                            <td style={{ padding: '10px', textAlign: 'center' }}>
                              <button 
                                onClick={() => void deleteCme(act.id)} 
                                className="secondary-button" 
                                style={{ minHeight: '32px', height: '32px', padding: '0 10px', fontSize: '13px', background: 'rgba(239, 68, 68, 0.1)', color: '#ef4444', borderColor: 'rgba(239, 68, 68, 0.2)' }}
                              >
                                Delete
                              </button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </article>
              </div>
            </div>
          )}
        </section>
      ) : null}

      <section style={{ padding: '0 24px 48px' }}>
        <div
          style={{
            maxWidth: '1120px',
            margin: '0 auto',
            display: 'flex',
            justifyContent: 'space-between',
            gap: '12px',
            flexWrap: 'wrap',
            color: '#94a3b8',
          }}
        >
          <span>Powered by Vibe-Tech. Legal stubs at /terms and /privacy.</span>
          <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
            <a href="/terms" style={{ color: '#67e8f9' }}>
              Terms
            </a>
            <a href="/privacy" style={{ color: '#67e8f9' }}>
              Privacy
            </a>
          </div>
        </div>
      </section>
    </main>
  );
}

function LegalPage({
  title,
  intro,
  sections,
}: {
  title: string;
  intro: string;
  sections: Array<{ heading: string; body: string }>;
}) {
  return (
    <main
      style={{
        minHeight: '100vh',
        padding: '48px 24px',
        background: '#08111f',
        color: '#f5f7fb',
        fontFamily: 'Inter, system-ui, sans-serif',
      }}
    >
      <div
        style={{
          maxWidth: '880px',
          margin: '0 auto',
          border: '1px solid rgba(148, 163, 184, 0.2)',
          borderRadius: '8px',
          background: 'rgba(15, 23, 42, 0.82)',
          padding: '24px',
        }}
      >
        <div
          style={{
            display: 'inline-block',
            marginBottom: '16px',
            padding: '6px 12px',
            borderRadius: '999px',
            background: 'rgba(14, 165, 233, 0.16)',
            color: '#67e8f9',
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
          }}
        >
          Factory legal stub
        </div>
        <h1 style={{ margin: '0 0 16px', fontSize: '40px', lineHeight: 1.1 }}>{title}</h1>
        <p style={{ margin: '0 0 24px', color: '#b7c3d6', lineHeight: 1.7 }}>{intro}</p>
        <div style={{ display: 'grid', gap: '20px' }}>
          {sections.map((section) => (
            <section key={section.heading}>
              <h2 style={{ margin: '0 0 8px', fontSize: '22px' }}>{section.heading}</h2>
              <p style={{ margin: 0, color: '#dbe4f2', lineHeight: 1.7 }}>{section.body}</p>
            </section>
          ))}
        </div>
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', marginTop: '24px' }}>
          <a href="/" style={{ color: '#67e8f9' }}>
            Back to app
          </a>
          <a href="/terms" style={{ color: '#67e8f9' }}>
            Terms
          </a>
          <a href="/privacy" style={{ color: '#67e8f9' }}>
            Privacy
          </a>
        </div>
      </div>
    </main>
  );
}
