import { createDefaultLandingContent } from '@vibetech/landing';

export const content = createDefaultLandingContent({
  productName: 'CME Track',
  badge: 'Generated by @vibetech/factory:saas',
  title: 'Continuing Education Credit Tracker',
  subtitle: 'Track CME credits, monitor certification targets, and secure your logs under CME Track Pro.',
  previewItems: ['Log CME Activity', 'Calculate total hours', 'Track progress to target', 'Export credits list'],
  featuresHeading: 'Core tracking features',
  featuresSubheading: 'Track CME Category 1/2 requirements and monitor remaining hours required to renew your professional license.',
  features: [
    { title: 'Activity log', description: 'Log title, credit hours, category, date, and provider in one secure vault.' },
    { title: 'Target monitoring', description: 'Visual progress meters tracking completion against standard 50-hour goals.' },
    { title: 'Secure entitlement', description: 'Logs and stats safely gated under the secure CME Track Pro SQLite data layer.' },
  ],
  ctaHeading: 'Start tracking CME requirements today',
  ctaBody: 'Subscribe to CME Track Pro to get unlimited logging and visual target tracking.',
  footerRight: 'Built with the VibeTech factory SaaS generator',
});

export interface GeneratedAuthUser {
  email: string;
  fullName?: string;
}

export interface CmeActivity {
  id: number;
  user_email: string;
  title: string;
  hours: number;
  category: string;
  date_earned: string;
  provider: string;
}
