import { createDefaultLandingContent } from '@vibetech/landing';

import type { ReviewInput } from './proposalTypes';

export const initialInput: ReviewInput = {
  clientName: 'Northwind Studio',
  projectType: 'Website redesign',
  proposalText:
    'This proposal covers discovery, timeline milestones, two feedback rounds, a 50% deposit, and an explicit out of scope section for extra pages.',
  priceUsd: '2200',
  turnaroundDays: '10',
  revisionRounds: '2',
};

export const landingContent = createDefaultLandingContent({
  productName: 'Proposal Review',
  badge: 'Generated by @vibetech/factory:saas',
  title: 'Proposal Review for freelancers and studios',
  subtitle:
    'Score client proposals before you send them, tighten scope boundaries, and upgrade to pro for rewrite guidance and follow-up checklists.',
  previewItems: ['Free scorecard', 'Pro rewrite guidance', 'Stripe checkout path', 'Shared factory packages'],
  featuresHeading: 'What the app does on day one',
  featuresSubheading:
    'This is a real micro-tool built from the factory scaffold, not just a placeholder landing page.',
  features: [
    {
      title: 'Free review',
      description: 'Score proposals on pricing, scope clarity, timeline language, and revision boundaries.',
    },
    {
      title: 'Pro rewrite',
      description: 'Unlock stronger CTA language, scope guardrails, and next-step checklists.',
    },
    {
      title: 'Monetization path',
      description: 'The generated app already includes a Stripe checkout route and factory metadata.',
    },
  ],
  pricingHeading: 'Simple pricing',
  pricingSubheading: 'Use the free scorecard first, then upgrade once the team needs rewrite help.',
  tiers: [
    {
      name: 'Free',
      price: '$0',
      subtitle: 'Quick proposal scorecard',
      features: ['Proposal score', 'Risk flags', 'Next-step recommendation'],
    },
    {
      name: 'Pro',
      price: '$19',
      subtitle: 'Per month, billed monthly',
      featured: true,
      features: ['Rewrite guidance', 'Scope guardrails', 'Follow-up checklist'],
    },
  ],
  faqHeading: 'Operational questions',
  faqSubheading: 'The tool is built for quick deal review, not full document management.',
  faqs: [
    {
      question: 'Does this replace proposal writing?',
      answer: 'No. It helps you tighten a proposal before it goes out and adds paid rewrite guidance for the final polish pass.',
    },
    {
      question: 'How does pro work right now?',
      answer: 'Pro guidance is surfaced through a gated route so the billing and entitlement path can be exercised in one app.',
    },
  ],
  ctaHeading: 'Review the next proposal before it leaves your desk',
  ctaBody:
    'Run the free scorecard below, then use the pro lane when a client proposal needs cleaner scope and stronger commercial language.',
  ctaAction: { label: 'Jump to review', href: '#review-tool' },
  footerRight: 'Built with the VibeTech factory SaaS generator',
});
