import { createDefaultLandingContent } from '@vibetech/landing';

import type { ReviewInput } from './proposalTypes';

export const initialInput: ReviewInput = {
  clientName: 'Northwind Studio',
  projectType: 'Website redesign',
  proposalText:
    'This proposal covers discovery, timeline milestones, two feedback rounds, a 50% deposit, and an explicit out of scope section for extra pages.',
  priceUsd: '2200',
  turnaroundDays: '10',
  revisionRounds: '2',
};

export const landingContent = createDefaultLandingContent({
  productName: 'Proposal Review',
  badge: 'Generated by @vibetech/factory:saas',
  title: 'Stop Losing Bids to Weak Proposals. Get a Free Scorecard.',
  subtitle:
    'Run a free diagnostic audit that scores scope, pricing, timeline, and close language before the proposal goes out. When the bid needs a stronger finish, unlock the premium rewrite for sharper positioning, CTA copy, and scope guardrails.',
  primaryAction: { label: 'Get My Free Scorecard', href: '#review-tool' },
  secondaryAction: { label: 'Unlock Pro Rewrite', href: '#pro-rewrite' },
  previewItems: [
    'Free diagnostic scorecard',
    'Gated pro rewrite',
    'Stripe checkout path',
    'Shared factory packages',
  ],
  featuresHeading: 'What the app does on day one',
  featuresSubheading:
    'Start with a no-cost proposal audit, then route high-value bids into the entitlement-gated rewrite lane.',
  features: [
    {
      title: 'Free scorecard',
      description:
        'Score proposals on pricing, scope clarity, timeline language, and revision boundaries before you send.',
    },
    {
      title: 'Pro rewrite',
      description:
        'Unlock stronger CTA language, buyer-ready summary copy, scope guardrails, and next-step checklists.',
    },
    {
      title: 'Monetization path',
      description: 'The generated app already includes a Stripe checkout route and factory metadata.',
    },
  ],
  pricingHeading: 'Simple pricing',
  pricingSubheading:
    'Use the free diagnostic first, then upgrade when a proposal needs rewrite help before the close.',
  tiers: [
    {
      name: 'Free',
      price: '$0',
      subtitle: 'Quick proposal scorecard',
      features: ['Proposal score', 'Risk flags', 'Next-step recommendation'],
    },
    {
      name: 'Pro',
      price: '$19',
      subtitle: 'Per month, billed monthly',
      featured: true,
      features: ['Rewrite guidance', 'Scope guardrails', 'Follow-up checklist'],
    },
  ],
  faqHeading: 'Operational questions',
  faqSubheading: 'The tool is built for quick deal review, not full document management.',
  faqs: [
    {
      question: 'Does this replace proposal writing?',
      answer: 'No. It helps you tighten a proposal before it goes out and adds paid rewrite guidance for the final polish pass.',
    },
    {
      question: 'How does pro work right now?',
      answer: 'Pro guidance is surfaced through a gated route so the billing and entitlement path can be exercised in one app.',
    },
  ],
  ctaHeading: 'Review the next proposal before it leaves your desk',
  ctaBody:
    'Get the free scorecard below, then unlock the pro rewrite when a client proposal needs cleaner scope and stronger commercial language.',
  ctaAction: { label: 'Get My Free Scorecard', href: '#review-tool' },
  footerRight: 'Built with the VibeTech factory SaaS generator',
});
