import type { AIModel, ModelConfig } from '@/types';

export const models: Record<AIModel, ModelConfig> = {
  'claude-opus-4-6': {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'Anthropic',
    context: 200000,
    maxOutput: 128000,
    thinking: true,
    strengths: ['SOTA reasoning', 'adaptive thinking', 'agentic coding', '1M context beta'],
  },
  'claude-sonnet-4-5': {
    id: 'claude-sonnet-4-5',
    name: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    context: 200000,
    maxOutput: 64000,
    thinking: true,
    strengths: ['balanced', 'fast coding', 'tool use', 'context awareness'],
  },
  'claude-haiku-4-5': {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    context: 200000,
    maxOutput: 64000,
    thinking: true,
    strengths: ['fastest', 'cost-effective', 'multi-agent', 'interactive'],
  },
  'gemini-3-pro': {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    provider: 'Google',
    context: 1000000,
    maxOutput: 65536,
    thinking: true,
    strengths: ['most intelligent', 'multimodal', 'agentic coding', 'less verbose'],
  },
  'gemini-2-5-flash': {
    id: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    context: 1000000,
    maxOutput: 65536,
    thinking: true,
    strengths: ['workhorse', 'fast', '1M context', 'thinking mode'],
  },
  'gemini-2-5-pro': {
    id: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    context: 1000000,
    maxOutput: 65536,
    thinking: true,
    strengths: ['enhanced thinking', 'code generation', 'structured output'],
  },
  'codex-5-3': {
    id: 'codex-5-3',
    name: 'Codex 5.3',
    provider: 'OpenAI',
    context: 128000,
    maxOutput: 16384,
    thinking: true,
    strengths: ['agentic coding', 'long-horizon tasks', 'debugging', 'cybersecurity'],
  },
  'codex-5-3-spark': {
    id: 'codex-5-3-spark',
    name: 'Codex 5.3 Spark',
    provider: 'OpenAI',
    context: 128000,
    maxOutput: 16384,
    thinking: false,
    strengths: ['ultra-fast', 'real-time edits', '1000+ tok/s', 'minimal changes'],
  },
};
