module.exports = {
	ci: {
		collect: {
			staticDistDir: "./dist",
			url: [
				"http://localhost:3000",
				"http://localhost:3000/search",
				"http://localhost:3000/hotel/1",
			],
			numberOfRuns: 3,
			settings: {
				preset: "desktop",
				throttling: {
					rttMs: 40,
					throughputKbps: 10240,
					cpuSlowdownMultiplier: 1,
				},
			},
		},
		assert: {
			preset: "lighthouse:recommended",
			assertions: {
				"categories:performance": ["error", { minScore: 0.9 }],
				"categories:accessibility": ["error", { minScore: 0.95 }],
				"categories:best-practices": ["error", { minScore: 0.95 }],
				"categories:seo": ["error", { minScore: 0.95 }],
				"categories:pwa": ["warn", { minScore: 0.9 }],
				"first-contentful-paint": ["error", { maxNumericValue: 1200 }],
				"largest-contentful-paint": ["error", { maxNumericValue: 2500 }],
				"cumulative-layout-shift": ["error", { maxNumericValue: 0.1 }],
				"total-blocking-time": ["error", { maxNumericValue: 300 }],
				"max-potential-fid": ["error", { maxNumericValue: 200 }],
				"errors-in-console": ["error", { minScore: 0 }],
				"no-unload-listeners": "error",
				"render-blocking-resources": ["warn", { maxLength: 0 }],
				"uses-rel-preconnect": "warn",
				"uses-rel-preload": "warn",
				"dom-size": ["warn", { maxNumericValue: 1500 }],
				"uses-long-cache-ttl": "warn",
				"offscreen-images": "warn",
				"unused-javascript": ["warn", { maxLength: 2 }],
				"uses-optimized-images": "warn",
				"uses-text-compression": "warn",
				"uses-responsive-images": "warn",
				"unminified-css": "error",
				"unminified-javascript": "error",
				"unused-css-rules": "warn",
				"modern-image-formats": "warn",
				"uses-passive-event-listeners": "error",
				"no-document-write": "error",
				"non-composited-animations": "warn",
				"bootup-time": ["warn", { maxNumericValue: 3500 }],
				"mainthread-work-breakdown": ["warn", { maxNumericValue: 4000 }],
				"font-display": "warn",
				"third-party-summary": "warn",
			},
		},
		upload: {
			target: "temporary-public-storage",
		},
	},
};
