const fs = require('fs');
const path = require('path');

const filePath = path.resolve(__dirname, '..', 'src', 'lib', 'tauri-bridge.ts');
let content = fs.readFileSync(filePath, 'utf8');

const regex = /const BROWSER_MOCK_APPS: VibeAppManifest\[\] = \[([\s\S]*?)\];/;

const replacement = `const BROWSER_MOCK_APPS: VibeAppManifest[] = [
  {
    id: 'nova-agent',
    name: 'Nova Agent',
    description: 'AI desktop assistant with RAG — 121/121 tests',
    icon: '/app-icons/nova-agent.png',
    category: 'ai',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 3000,
    app_type: 'native',
  },
  {
    id: 'vibe-code-studio',
    name: 'Vibe Code Studio',
    description: 'AI-powered IDE with 27+ models',
    icon: '/app-icons/vibe-code-studio.png',
    category: 'dev',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 5173,
    app_type: 'native',
  },
  {
    id: 'vtde',
    name: 'VTDE',
    description: 'Tauri 2.0 desktop environment (self)',
    icon: '/app-icons/vtde.png',
    category: 'dev',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 1420,
    app_type: 'native',
  },
  {
    id: 'nova-mobile-app',
    name: 'Nova Mobile',
    description: 'Mobile companion app — HTTP bridge',
    icon: '/app-icons/nova-mobile-app.png',
    category: 'ai',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 3001,
    app_type: 'web',
  },
  {
    id: 'vibe-tutor',
    name: 'Vibe Tutor',
    description: 'Educational Assistant',
    icon: '/app-icons/vibe-tutor.png',
    category: 'education',
    version: '8.2.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 5174,
    app_type: 'web',
  },
  {
    id: 'memory-mcp',
    name: 'Memory MCP',
    description: 'Memory system — 56/56 tests',
    icon: '/app-icons/memory-mcp.png',
    category: 'ai',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 3002,
    app_type: 'native',
  },
  {
    id: 'desktop-commander-v3',
    name: 'Desktop Commander',
    description: 'MCP server for system control',
    icon: '/app-icons/desktop-commander-v3.png',
    category: 'dev',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 3003,
    app_type: 'native',
  },
  {
    id: 'vibe-justice',
    name: 'Vibe Justice',
    description: 'Legal case management assistant',
    icon: '/app-icons/vibe-justice.png',
    category: 'business',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 3004,
    app_type: 'web',
  },
  {
    id: 'crypto-enhanced',
    name: 'Crypto Enhanced',
    description: 'Cryptocurrency trading bot',
    icon: '/app-icons/crypto-enhanced.png',
    category: 'finance',
    version: '1.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 3005,
    app_type: 'web',
  },
  {
    id: 'vibe-shop',
    name: 'Vibe Shop',
    description: 'AI e-commerce platform',
    icon: '/app-icons/vibe-shop.png',
    category: 'business',
    version: '2.0.0',
    status: 'active',
    launch_cmd: 'pnpm dev',
    features: ['vtde-autodiscovered'],
    port: 5000,
    app_type: 'web',
  },
];`;

content = content.replace(regex, replacement);
fs.writeFileSync(filePath, content, 'utf8');
console.warn('Update complete');
