import {
  LandingPage,
  createDefaultLandingContent,
} from '@vibetech/landing';

const content = createDefaultLandingContent({
  productName: 'FactorySaasSmoke',
  badge: 'Generated by @vibetech/factory:saas',
  title: 'FactorySaasSmoke',
  subtitle:
    'This scaffold includes a React frontend, a Fastify API, and a first entitlement-aware API surface.',
  previewItems: ['Shared landing page', 'Fastify API', 'Pro route gate', 'Workspace package wiring'],
  featuresHeading: 'Factory defaults for monetized apps',
  featuresSubheading:
    'The generator starts with shared landing content, auth and entitlement package dependencies, and a first gated backend route.',
  features: [
    {
      title: 'Landing package',
      description: 'The frontend starts on the shared landing system instead of placeholder copy.',
    },
    {
      title: 'Auth seam',
      description: 'The generated app is already positioned to adopt @vibetech/auth.',
    },
    {
      title: 'Entitlement seam',
      description: 'The generated API includes a first plan-gated route under /api/pro.',
    },
  ],
  ctaHeading: 'Start from shared monetization primitives',
  ctaBody:
    'Replace the copy and plan details, then move straight into product-specific workflow work.',
  footerRight: 'Built with the VibeTech factory SaaS generator',
});

export function App() {
  return <LandingPage content={content} />;
}
