import { useMemo, useState } from 'react';
import { activateLicense } from '@vibetech/billing/client';

const appId = 'factory-tauri-smoke';
const activationUrl = import.meta.env.VITE_BILLING_ACTIVATION_URL;

export function App() {
  const [licenseKey, setLicenseKey] = useState('DEMO-TAURI-1234');
  const [deviceName, setDeviceName] = useState('This device');
  const [status, setStatus] = useState<'idle' | 'activating' | 'active' | 'error'>('idle');
  const [message, setMessage] = useState('Use a DEMO- key locally or set VITE_BILLING_ACTIVATION_URL.');

  const canActivate = useMemo(() => licenseKey.trim().length > 0, [licenseKey]);

  const handleActivate = async () => {
    if (!canActivate) {
      return;
    }

    setStatus('activating');
    setMessage('Activating license...');

    try {
      const result = await activateLicense({
        appId,
        licenseKey,
        activationUrl,
        deviceName,
      });
      setStatus('active');
      setLicenseKey(result.licenseKey);
      setMessage(`Activated ${result.licenseKey} for ${result.deviceName ?? 'this device'}.`);
    } catch (error) {
      setStatus('error');
      setMessage(error instanceof Error ? error.message : String(error));
    }
  };

  return (
    <main className="page">
      <div className="eyebrow">Generated by @vibetech/factory:tauri-app</div>
      <h1>FactoryTauriSmoke</h1>
      <p className="lede">Desktop shell scaffold with a billing-backed license activation seam.</p>

      <section className="activation-panel">
        <div className="field">
          <label htmlFor="licenseKey">License key</label>
          <input
            id="licenseKey"
            value={licenseKey}
            onChange={(event) => setLicenseKey(event.target.value)}
            spellCheck={false}
          />
        </div>
        <div className="field">
          <label htmlFor="deviceName">Device name</label>
          <input
            id="deviceName"
            value={deviceName}
            onChange={(event) => setDeviceName(event.target.value)}
            spellCheck={false}
          />
        </div>
        <button
          type="button"
          className="activate-button"
          disabled={!canActivate || status === 'activating'}
          onClick={() => {
            void handleActivate();
          }}
        >
          {status === 'activating' ? 'Activating...' : 'Activate license'}
        </button>
        <p className={`status status-${status}`}>{message}</p>
      </section>
    </main>
  );
}
