/* eslint-disable react-refresh/only-export-components */

import type { CSSProperties, ReactNode } from 'react';

export interface LandingAction {
  label: string;
  href: string;
}

export interface LandingFeature {
  title: string;
  description: string;
}

export interface LandingTier {
  name: string;
  price: string;
  subtitle: string;
  features: readonly string[];
  featured?: boolean;
}

export interface LandingFaq {
  question: string;
  answer: string;
}

export interface LandingContent {
  productName: string;
  badge: string;
  title: string;
  subtitle: string;
  primaryAction: LandingAction;
  secondaryAction?: LandingAction;
  previewLabel: string;
  previewItems: readonly string[];
  featuresHeading: string;
  featuresSubheading: string;
  features: readonly LandingFeature[];
  pricingHeading: string;
  pricingSubheading: string;
  tiers: readonly LandingTier[];
  faqHeading: string;
  faqSubheading: string;
  faqs: readonly LandingFaq[];
  ctaHeading: string;
  ctaBody: string;
  ctaAction: LandingAction;
  footerLeft: string;
  footerRight: string;
}

export interface LandingPageProps {
  content: LandingContent;
}

const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    background:
      'radial-gradient(circle at top, rgba(37, 99, 235, 0.18), transparent 28rem), #08111f',
    color: '#f5f7fb',
    fontFamily: 'Inter, system-ui, sans-serif',
  },
  container: {
    maxWidth: '1120px',
    margin: '0 auto',
    padding: '0 24px',
  },
  hero: {
    padding: '80px 0 64px',
    display: 'grid',
    gap: '24px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    alignItems: 'start',
  },
  badge: {
    display: 'inline-block',
    marginBottom: '16px',
    padding: '6px 12px',
    borderRadius: '999px',
    background: 'rgba(14, 165, 233, 0.16)',
    color: '#67e8f9',
    fontSize: '12px',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  heroTitle: {
    margin: '0 0 16px',
    fontSize: '56px',
    lineHeight: 1,
  },
  heroBody: {
    margin: '0 0 24px',
    fontSize: '18px',
    lineHeight: 1.6,
    color: '#b7c3d6',
  },
  row: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '42px',
    padding: '0 16px',
    borderRadius: '8px',
    textDecoration: 'none',
    fontWeight: 600,
    fontSize: '14px',
  },
  primaryButton: {
    background: '#22d3ee',
    color: '#062133',
  },
  secondaryButton: {
    border: '1px solid rgba(148, 163, 184, 0.32)',
    color: '#e2e8f0',
    background: 'rgba(15, 23, 42, 0.5)',
  },
  card: {
    border: '1px solid rgba(148, 163, 184, 0.2)',
    borderRadius: '8px',
    background: 'rgba(15, 23, 42, 0.72)',
    padding: '20px',
  },
  section: {
    padding: '24px 0 64px',
  },
  sectionHeader: {
    marginBottom: '24px',
  },
  sectionTitle: {
    margin: '0 0 12px',
    fontSize: '36px',
    lineHeight: 1.1,
  },
  sectionBody: {
    margin: 0,
    color: '#b7c3d6',
    fontSize: '16px',
    lineHeight: 1.6,
    maxWidth: '720px',
  },
  grid: {
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
  },
  tierName: {
    margin: '0 0 8px',
    fontSize: '20px',
  },
  tierPrice: {
    margin: '0 0 8px',
    fontSize: '32px',
    fontWeight: 700,
  },
  muted: {
    color: '#94a3b8',
    fontSize: '14px',
  },
  list: {
    margin: '16px 0 0',
    paddingLeft: '18px',
    color: '#dbe4f2',
    lineHeight: 1.7,
  },
  featured: {
    borderColor: 'rgba(34, 211, 238, 0.45)',
    boxShadow: '0 0 0 1px rgba(34, 211, 238, 0.16)',
  },
  label: {
    display: 'inline-block',
    marginBottom: '10px',
    padding: '4px 10px',
    borderRadius: '999px',
    background: 'rgba(34, 211, 238, 0.14)',
    color: '#67e8f9',
    fontSize: '11px',
    textTransform: 'uppercase',
  },
  footer: {
    borderTop: '1px solid rgba(148, 163, 184, 0.16)',
    padding: '24px 0 48px',
    color: '#94a3b8',
    fontSize: '14px',
  },
  footerInner: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
  },
};

export function createDefaultLandingContent(
  overrides: Partial<LandingContent> = {},
): LandingContent {
  return {
    productName: overrides.productName ?? 'VibeTech App',
    badge: overrides.badge ?? 'Generated by @vibetech/landing',
    title: overrides.title ?? 'Launch a monetized app without rebuilding the basics',
    subtitle:
      overrides.subtitle ??
      'Start from a shared landing system with pricing, conversion sections, and legal-friendly structure already in place.',
    primaryAction: overrides.primaryAction ?? { label: 'Get started', href: '/signup' },
    secondaryAction: overrides.secondaryAction ?? { label: 'Log in', href: '/login' },
    previewLabel: overrides.previewLabel ?? 'Preview',
    previewItems:
      overrides.previewItems ?? ['Hero section', 'Pricing tiers', 'FAQ section', 'Conversion CTA'],
    featuresHeading: overrides.featuresHeading ?? 'Core sections already wired',
    featuresSubheading:
      overrides.featuresSubheading ??
      'Swap the copy and feature details for the product without rebuilding the page structure.',
    features:
      overrides.features ??
      [
        {
          title: 'Pricing-ready layout',
          description: 'Drop in free, pro, and team plans with a stable information hierarchy.',
        },
        {
          title: 'Conversion sections',
          description: 'Hero, feature grid, FAQ, CTA, and footer are already composed.',
        },
        {
          title: 'Factory-friendly',
          description: 'Designed to be consumed by generated apps and later shared across products.',
        },
      ],
    pricingHeading: overrides.pricingHeading ?? 'Pricing that scales with usage',
    pricingSubheading:
      overrides.pricingSubheading ??
      'Start with a simple free tier, then unlock the paid automation surface when users are ready.',
    tiers:
      overrides.tiers ??
      [
        {
          name: 'Starter',
          price: '$0',
          subtitle: 'For first-time users and evaluation',
          features: ['Core workflow', 'Basic exports', 'Single-user access'],
        },
        {
          name: 'Pro',
          price: '$19',
          subtitle: 'Per month, billed monthly',
          featured: true,
          features: ['Automation', 'Recurring workflows', 'Analytics events'],
        },
        {
          name: 'Team',
          price: '$49',
          subtitle: 'Per month, billed monthly',
          features: ['Multi-user access', 'Admin controls', 'Priority support'],
        },
      ],
    faqHeading: overrides.faqHeading ?? 'Questions teams usually ask first',
    faqSubheading:
      overrides.faqSubheading ??
      'Keep the FAQ short and operational. It should remove buyer friction, not explain the whole app.',
    faqs:
      overrides.faqs ??
      [
        {
          question: 'Can I start without a credit card?',
          answer: 'Yes. The free tier exists so the first workflow can be evaluated before billing is relevant.',
        },
        {
          question: 'When do paid features unlock?',
          answer: 'As soon as the account plan changes, entitlement-gated routes can allow the new workflow surface.',
        },
      ],
    ctaHeading: overrides.ctaHeading ?? 'Ship the first paying workflow faster',
    ctaBody:
      overrides.ctaBody ??
      'Use the shared packages for auth, entitlements, and billing so the app can focus on the product feature surface.',
    ctaAction: overrides.ctaAction ?? { label: 'Create account', href: '/signup' },
    footerLeft: overrides.footerLeft ?? `© ${new Date().getFullYear()} ${overrides.productName ?? 'VibeTech App'}`,
    footerRight: overrides.footerRight ?? 'Built with the VibeTech app factory',
  };
}

export function LandingPage({ content }: LandingPageProps) {
  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <section style={styles.hero}>
          <div>
            <div style={styles.badge}>{content.badge}</div>
            <h1 style={styles.heroTitle}>{content.title}</h1>
            <p style={styles.heroBody}>{content.subtitle}</p>
            <div style={styles.row}>
              <ActionLink action={content.primaryAction} primary />
              {content.secondaryAction ? <ActionLink action={content.secondaryAction} /> : null}
            </div>
          </div>
          <SectionCard label={content.previewLabel}>
            <ul style={styles.list}>
              {content.previewItems.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </SectionCard>
        </section>

        <LandingSection title={content.featuresHeading} subtitle={content.featuresSubheading}>
          <div style={styles.grid}>
            {content.features.map((feature) => (
              <SectionCard key={feature.title}>
                <h3 style={styles.tierName}>{feature.title}</h3>
                <p style={styles.sectionBody}>{feature.description}</p>
              </SectionCard>
            ))}
          </div>
        </LandingSection>

        <LandingSection title={content.pricingHeading} subtitle={content.pricingSubheading}>
          <div style={styles.grid}>
            {content.tiers.map((tier) => (
              <SectionCard key={tier.name} label={tier.featured ? 'Most popular' : undefined} featured={tier.featured}>
                <h3 style={styles.tierName}>{tier.name}</h3>
                <div style={styles.tierPrice}>{tier.price}</div>
                <div style={styles.muted}>{tier.subtitle}</div>
                <ul style={styles.list}>
                  {tier.features.map((feature) => (
                    <li key={feature}>{feature}</li>
                  ))}
                </ul>
              </SectionCard>
            ))}
          </div>
        </LandingSection>

        <LandingSection title={content.faqHeading} subtitle={content.faqSubheading}>
          <div style={styles.grid}>
            {content.faqs.map((faq) => (
              <SectionCard key={faq.question}>
                <h3 style={styles.tierName}>{faq.question}</h3>
                <p style={styles.sectionBody}>{faq.answer}</p>
              </SectionCard>
            ))}
          </div>
        </LandingSection>

        <section style={{ ...styles.section, paddingTop: 0 }}>
          <SectionCard>
            <div style={styles.row}>
              <div style={{ flex: 1, minWidth: '260px' }}>
                <h2 style={styles.sectionTitle}>{content.ctaHeading}</h2>
                <p style={styles.sectionBody}>{content.ctaBody}</p>
              </div>
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <ActionLink action={content.ctaAction} primary />
              </div>
            </div>
          </SectionCard>
        </section>

        <footer style={styles.footer}>
          <div style={styles.footerInner}>
            <span>{content.footerLeft}</span>
            <span>{content.footerRight}</span>
          </div>
        </footer>
      </div>
    </div>
  );
}

function LandingSection({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle: string;
  children: ReactNode;
}) {
  return (
    <section style={styles.section}>
      <div style={styles.sectionHeader}>
        <h2 style={styles.sectionTitle}>{title}</h2>
        <p style={styles.sectionBody}>{subtitle}</p>
      </div>
      {children}
    </section>
  );
}

function SectionCard({
  children,
  label,
  featured = false,
}: {
  children: ReactNode;
  label?: string;
  featured?: boolean;
}) {
  return (
    <article style={{ ...styles.card, ...(featured ? styles.featured : {}) }}>
      {label ? <div style={styles.label}>{label}</div> : null}
      {children}
    </article>
  );
}

function ActionLink({
  action,
  primary = false,
}: {
  action: LandingAction;
  primary?: boolean;
}) {
  return (
    <a
      href={action.href}
      style={{
        ...styles.button,
        ...(primary ? styles.primaryButton : styles.secondaryButton),
      }}
    >
      {action.label}
    </a>
  );
}
