/**
 * WebMCP Tool Definitions
 * Auto-generated by webmcp-autogen
 * Generated: 2026-06-10T20:38:06.225Z
 *
 * Usage: Include this script on your page to register tools
 * with the browser's Model Context Protocol.
 */

// Check for WebMCP API support (Chrome 146+)
declare global {
  interface Navigator {
    modelContext?: {
      registerTool(def: {
        name: string;
        description: string;
        inputSchema: Record<string, unknown>;
        annotations?: Record<string, string>;
        execute: (params: Record<string, unknown>) => Promise<{ content: Array<{ type: string; text: string }> }>;
      }): void;
      unregisterTool(name: string): void;
    };
  }
}

export function initWebMCPTools() {
  if (!navigator.modelContext) {
    console.warn("[WebMCP] navigator.modelContext not available. Ensure Chrome 146+ with experimental features enabled.");
    return;
  }

  // Tool: localhost_search_form
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_search_form",
    description: "Submit a form with 1 field on localhost/.",
    inputSchema: {
      "type": "object",
      "properties": {
        "q": {
          "type": "string",
          "description": "Search products..."
        }
      }
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (params: Record<string, unknown>) => {

      // Fill form fields
      const form = document.querySelector("html > body > main > header > div > div > form");
      if (!form) throw new Error("Form not found: html > body > main > header > div > div > form");

      const qInput = form.querySelector('[name="q"]');
      if (qInput) {
        (qInput as HTMLInputElement).value = String(params["q"] ?? "");
        qInput.dispatchEvent(new Event("input", { bubbles: true }));
      }

      // Click element
      const clickTarget = document.querySelector("html > body > main > header > div > div > form button");
      if (clickTarget) {
        (clickTarget as HTMLElement).click();
      }

      // Wait for network response
      await new Promise((resolve, reject) => {
        const timeout = setTimeout(() => reject(new Error("Network timeout")), 10000);
        const origFetch = window.fetch;
        window.fetch = async (...args) => {
          const res = await origFetch(...args);
          if (String(args[0]).includes("http://localhost:3010/")) {
            clearTimeout(timeout);
            window.fetch = origFetch;
            resolve(res.clone());
          }
          return res;
        };
      });

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_click_menu
  // Safety: write (requires confirmation)
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_click_menu",
    description: "Click Open menu on localhost/.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    execute: async (_params: Record<string, unknown>) => {

      // Click element
      const clickTarget = document.querySelector("html > body > main > header > div > div > button");
      if (clickTarget) {
        (clickTarget as HTMLElement).click();
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_electronics
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_electronics",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/electronics.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/electronics")) {
        window.location.href = "http://localhost:3010/category/electronics";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_homegarden
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_homegarden",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/home-garden.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/home-garden")) {
        window.location.href = "http://localhost:3010/category/home-garden";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_fashion
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_fashion",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/fashion.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/fashion")) {
        window.location.href = "http://localhost:3010/category/fashion";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_toyshobbies
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_toyshobbies",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/toys-hobbies.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/toys-hobbies")) {
        window.location.href = "http://localhost:3010/category/toys-hobbies";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_sports
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_sports",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/sports.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/sports")) {
        window.location.href = "http://localhost:3010/category/sports";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_search
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_search",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/search.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/search")) {
        window.location.href = "http://localhost:3010/search";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_automotive
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_automotive",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/automotive.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/automotive")) {
        window.location.href = "http://localhost:3010/category/automotive";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_beauty
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_beauty",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/beauty.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/beauty")) {
        window.location.href = "http://localhost:3010/category/beauty";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_toys
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_toys",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/category/toys.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/toys")) {
        window.location.href = "http://localhost:3010/category/toys";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_6fe21b7e08994ee3be573f7930931c
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_6fe21b7e08994ee3be573f7930931c",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/6fe21b7e-0899-4ee3-be57-3f7930931cc9.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/6fe21b7e-0899-4ee3-be57-3f7930931cc9")) {
        window.location.href = "http://localhost:3010/product/6fe21b7e-0899-4ee3-be57-3f7930931cc9";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_ed780dd9cb68400ab6d21c76e18d42
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_ed780dd9cb68400ab6d21c76e18d42",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/ed780dd9-cb68-400a-b6d2-1c76e18d42c9.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/ed780dd9-cb68-400a-b6d2-1c76e18d42c9")) {
        window.location.href = "http://localhost:3010/product/ed780dd9-cb68-400a-b6d2-1c76e18d42c9";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_5851b7d5a32e41a3b97b9079ec8468
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_5851b7d5a32e41a3b97b9079ec8468",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/5851b7d5-a32e-41a3-b97b-9079ec846801.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/5851b7d5-a32e-41a3-b97b-9079ec846801")) {
        window.location.href = "http://localhost:3010/product/5851b7d5-a32e-41a3-b97b-9079ec846801";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_15d1a544c3b44e7d810a7f27abd433
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_15d1a544c3b44e7d810a7f27abd433",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/15d1a544-c3b4-4e7d-810a-7f27abd43322.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/15d1a544-c3b4-4e7d-810a-7f27abd43322")) {
        window.location.href = "http://localhost:3010/product/15d1a544-c3b4-4e7d-810a-7f27abd43322";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_7a524543f72f4591addaa9d897b9f1
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_7a524543f72f4591addaa9d897b9f1",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/7a524543-f72f-4591-adda-a9d897b9f14f.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/7a524543-f72f-4591-adda-a9d897b9f14f")) {
        window.location.href = "http://localhost:3010/product/7a524543-f72f-4591-adda-a9d897b9f14f";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_18df226a824b4640a44407ae1d3a14
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_18df226a824b4640a44407ae1d3a14",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/18df226a-824b-4640-a444-07ae1d3a14c1.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/18df226a-824b-4640-a444-07ae1d3a14c1")) {
        window.location.href = "http://localhost:3010/product/18df226a-824b-4640-a444-07ae1d3a14c1";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_35ef3cbc2c9149c7950244b8aa6706
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_35ef3cbc2c9149c7950244b8aa6706",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/35ef3cbc-2c91-49c7-9502-44b8aa670638.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/35ef3cbc-2c91-49c7-9502-44b8aa670638")) {
        window.location.href = "http://localhost:3010/product/35ef3cbc-2c91-49c7-9502-44b8aa670638";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_7b02a9dc91724d16974012054a822f
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_7b02a9dc91724d16974012054a822f",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/product/7b02a9dc-9172-4d16-9740-12054a822f67.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/7b02a9dc-9172-4d16-9740-12054a822f67")) {
        window.location.href = "http://localhost:3010/product/7b02a9dc-9172-4d16-9740-12054a822f67";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_about
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_about",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/about.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/about")) {
        window.location.href = "http://localhost:3010/about";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_howitworks
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_howitworks",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/how-it-works.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/how-it-works")) {
        window.location.href = "http://localhost:3010/how-it-works";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_contact
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_contact",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/contact.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/contact")) {
        window.location.href = "http://localhost:3010/contact";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_affiliatedisclosure
  // Safety: read
  // Source: http://localhost:3010/
  navigator.modelContext.registerTool({
    name: "localhost_navigate_affiliatedisclosure",
    description: "Navigate from http://localhost:3010/ to http://localhost:3010/affiliate-disclosure.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/affiliate-disclosure")) {
        window.location.href = "http://localhost:3010/affiliate-disclosure";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_d00f91ef95694b01932da56bc53970
  // Safety: read
  // Source: http://localhost:3010/category/electronics
  navigator.modelContext.registerTool({
    name: "localhost_navigate_d00f91ef95694b01932da56bc53970",
    description: "Navigate from http://localhost:3010/category/electronics to http://localhost:3010/product/d00f91ef-9569-4b01-932d-a56bc539700b.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/electronics")) {
        window.location.href = "http://localhost:3010/category/electronics";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/d00f91ef-9569-4b01-932d-a56bc539700b")) {
        window.location.href = "http://localhost:3010/product/d00f91ef-9569-4b01-932d-a56bc539700b";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_ef0a646508de40a28f77bc89dcb9ae
  // Safety: read
  // Source: http://localhost:3010/category/electronics
  navigator.modelContext.registerTool({
    name: "localhost_navigate_ef0a646508de40a28f77bc89dcb9ae",
    description: "Navigate from http://localhost:3010/category/electronics to http://localhost:3010/product/ef0a6465-08de-40a2-8f77-bc89dcb9ae4f.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/electronics")) {
        window.location.href = "http://localhost:3010/category/electronics";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/ef0a6465-08de-40a2-8f77-bc89dcb9ae4f")) {
        window.location.href = "http://localhost:3010/product/ef0a6465-08de-40a2-8f77-bc89dcb9ae4f";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_82ac565edb6b4b0f9b4114e2c4bd23
  // Safety: read
  // Source: http://localhost:3010/category/electronics
  navigator.modelContext.registerTool({
    name: "localhost_navigate_82ac565edb6b4b0f9b4114e2c4bd23",
    description: "Navigate from http://localhost:3010/category/electronics to http://localhost:3010/product/82ac565e-db6b-4b0f-9b41-14e2c4bd235b.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/electronics")) {
        window.location.href = "http://localhost:3010/category/electronics";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/82ac565e-db6b-4b0f-9b41-14e2c4bd235b")) {
        window.location.href = "http://localhost:3010/product/82ac565e-db6b-4b0f-9b41-14e2c4bd235b";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_page
  // Safety: read
  // Source: http://localhost:3010/category/electronics
  navigator.modelContext.registerTool({
    name: "localhost_navigate_page",
    description: "Navigate from http://localhost:3010/category/electronics to http://localhost:3010/.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/electronics")) {
        window.location.href = "http://localhost:3010/category/electronics";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }


      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_6432daa611634e0c8647e5fdd2feb2
  // Safety: read
  // Source: http://localhost:3010/category/home-garden
  navigator.modelContext.registerTool({
    name: "localhost_navigate_6432daa611634e0c8647e5fdd2feb2",
    description: "Navigate from http://localhost:3010/category/home-garden to http://localhost:3010/product/6432daa6-1163-4e0c-8647-e5fdd2feb2e4.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/home-garden")) {
        window.location.href = "http://localhost:3010/category/home-garden";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/6432daa6-1163-4e0c-8647-e5fdd2feb2e4")) {
        window.location.href = "http://localhost:3010/product/6432daa6-1163-4e0c-8647-e5fdd2feb2e4";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_60b24aa2ca7943bb8ca0301e74fbb1
  // Safety: read
  // Source: http://localhost:3010/category/home-garden
  navigator.modelContext.registerTool({
    name: "localhost_navigate_60b24aa2ca7943bb8ca0301e74fbb1",
    description: "Navigate from http://localhost:3010/category/home-garden to http://localhost:3010/product/60b24aa2-ca79-43bb-8ca0-301e74fbb1f0.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/home-garden")) {
        window.location.href = "http://localhost:3010/category/home-garden";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/60b24aa2-ca79-43bb-8ca0-301e74fbb1f0")) {
        window.location.href = "http://localhost:3010/product/60b24aa2-ca79-43bb-8ca0-301e74fbb1f0";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_b9d5d9b0faa1465f820883252459be
  // Safety: read
  // Source: http://localhost:3010/category/home-garden
  navigator.modelContext.registerTool({
    name: "localhost_navigate_b9d5d9b0faa1465f820883252459be",
    description: "Navigate from http://localhost:3010/category/home-garden to http://localhost:3010/product/b9d5d9b0-faa1-465f-8208-83252459be29.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/home-garden")) {
        window.location.href = "http://localhost:3010/category/home-garden";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/b9d5d9b0-faa1-465f-8208-83252459be29")) {
        window.location.href = "http://localhost:3010/product/b9d5d9b0-faa1-465f-8208-83252459be29";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_68a4f6b64e8b468da6735c6d91e55f
  // Safety: read
  // Source: http://localhost:3010/category/fashion
  navigator.modelContext.registerTool({
    name: "localhost_navigate_68a4f6b64e8b468da6735c6d91e55f",
    description: "Navigate from http://localhost:3010/category/fashion to http://localhost:3010/product/68a4f6b6-4e8b-468d-a673-5c6d91e55f2a.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/fashion")) {
        window.location.href = "http://localhost:3010/category/fashion";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/68a4f6b6-4e8b-468d-a673-5c6d91e55f2a")) {
        window.location.href = "http://localhost:3010/product/68a4f6b6-4e8b-468d-a673-5c6d91e55f2a";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_6aadda0930d84304aeb8a5bfc0d14d
  // Safety: read
  // Source: http://localhost:3010/category/fashion
  navigator.modelContext.registerTool({
    name: "localhost_navigate_6aadda0930d84304aeb8a5bfc0d14d",
    description: "Navigate from http://localhost:3010/category/fashion to http://localhost:3010/product/6aadda09-30d8-4304-aeb8-a5bfc0d14de1.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/fashion")) {
        window.location.href = "http://localhost:3010/category/fashion";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/6aadda09-30d8-4304-aeb8-a5bfc0d14de1")) {
        window.location.href = "http://localhost:3010/product/6aadda09-30d8-4304-aeb8-a5bfc0d14de1";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_792911a4ea614f7987f5be997b039b
  // Safety: read
  // Source: http://localhost:3010/category/fashion
  navigator.modelContext.registerTool({
    name: "localhost_navigate_792911a4ea614f7987f5be997b039b",
    description: "Navigate from http://localhost:3010/category/fashion to http://localhost:3010/product/792911a4-ea61-4f79-87f5-be997b039b53.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/fashion")) {
        window.location.href = "http://localhost:3010/category/fashion";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/792911a4-ea61-4f79-87f5-be997b039b53")) {
        window.location.href = "http://localhost:3010/product/792911a4-ea61-4f79-87f5-be997b039b53";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_5529ec0030f9477da0514f76a95e3e
  // Safety: read
  // Source: http://localhost:3010/category/fashion
  navigator.modelContext.registerTool({
    name: "localhost_navigate_5529ec0030f9477da0514f76a95e3e",
    description: "Navigate from http://localhost:3010/category/fashion to http://localhost:3010/product/5529ec00-30f9-477d-a051-4f76a95e3e07.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/fashion")) {
        window.location.href = "http://localhost:3010/category/fashion";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/5529ec00-30f9-477d-a051-4f76a95e3e07")) {
        window.location.href = "http://localhost:3010/product/5529ec00-30f9-477d-a051-4f76a95e3e07";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_f0117e2d68044f0780b122d5f1b8cc
  // Safety: read
  // Source: http://localhost:3010/category/fashion
  navigator.modelContext.registerTool({
    name: "localhost_navigate_f0117e2d68044f0780b122d5f1b8cc",
    description: "Navigate from http://localhost:3010/category/fashion to http://localhost:3010/product/f0117e2d-6804-4f07-80b1-22d5f1b8cccc.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/fashion")) {
        window.location.href = "http://localhost:3010/category/fashion";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/f0117e2d-6804-4f07-80b1-22d5f1b8cccc")) {
        window.location.href = "http://localhost:3010/product/f0117e2d-6804-4f07-80b1-22d5f1b8cccc";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_aaf78a207a3c418fa643fd94e4bc29
  // Safety: read
  // Source: http://localhost:3010/category/sports
  navigator.modelContext.registerTool({
    name: "localhost_navigate_aaf78a207a3c418fa643fd94e4bc29",
    description: "Navigate from http://localhost:3010/category/sports to http://localhost:3010/product/aaf78a20-7a3c-418f-a643-fd94e4bc2924.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/sports")) {
        window.location.href = "http://localhost:3010/category/sports";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/aaf78a20-7a3c-418f-a643-fd94e4bc2924")) {
        window.location.href = "http://localhost:3010/product/aaf78a20-7a3c-418f-a643-fd94e4bc2924";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_07038ba36df941abbf6494f2e82b1f
  // Safety: read
  // Source: http://localhost:3010/category/sports
  navigator.modelContext.registerTool({
    name: "localhost_navigate_07038ba36df941abbf6494f2e82b1f",
    description: "Navigate from http://localhost:3010/category/sports to http://localhost:3010/product/07038ba3-6df9-41ab-bf64-94f2e82b1f48.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/sports")) {
        window.location.href = "http://localhost:3010/category/sports";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/07038ba3-6df9-41ab-bf64-94f2e82b1f48")) {
        window.location.href = "http://localhost:3010/product/07038ba3-6df9-41ab-bf64-94f2e82b1f48";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_de12341707914a6a8fb5317d710148
  // Safety: read
  // Source: http://localhost:3010/category/sports
  navigator.modelContext.registerTool({
    name: "localhost_navigate_de12341707914a6a8fb5317d710148",
    description: "Navigate from http://localhost:3010/category/sports to http://localhost:3010/product/de123417-0791-4a6a-8fb5-317d7101488c.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/sports")) {
        window.location.href = "http://localhost:3010/category/sports";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/de123417-0791-4a6a-8fb5-317d7101488c")) {
        window.location.href = "http://localhost:3010/product/de123417-0791-4a6a-8fb5-317d7101488c";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_a0e2c518b2704010b79085f2032ba4
  // Safety: read
  // Source: http://localhost:3010/category/sports
  navigator.modelContext.registerTool({
    name: "localhost_navigate_a0e2c518b2704010b79085f2032ba4",
    description: "Navigate from http://localhost:3010/category/sports to http://localhost:3010/product/a0e2c518-b270-4010-b790-85f2032ba459.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/sports")) {
        window.location.href = "http://localhost:3010/category/sports";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/a0e2c518-b270-4010-b790-85f2032ba459")) {
        window.location.href = "http://localhost:3010/product/a0e2c518-b270-4010-b790-85f2032ba459";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_2f8a3e6cebe344ee8d27cf76327a09
  // Safety: read
  // Source: http://localhost:3010/category/sports
  navigator.modelContext.registerTool({
    name: "localhost_navigate_2f8a3e6cebe344ee8d27cf76327a09",
    description: "Navigate from http://localhost:3010/category/sports to http://localhost:3010/product/2f8a3e6c-ebe3-44ee-8d27-cf76327a0958.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/sports")) {
        window.location.href = "http://localhost:3010/category/sports";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/2f8a3e6c-ebe3-44ee-8d27-cf76327a0958")) {
        window.location.href = "http://localhost:3010/product/2f8a3e6c-ebe3-44ee-8d27-cf76327a0958";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_9652c1fa3f69498fbb68d7ada2f50f
  // Safety: read
  // Source: http://localhost:3010/category/automotive
  navigator.modelContext.registerTool({
    name: "localhost_navigate_9652c1fa3f69498fbb68d7ada2f50f",
    description: "Navigate from http://localhost:3010/category/automotive to http://localhost:3010/product/9652c1fa-3f69-498f-bb68-d7ada2f50fba.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/automotive")) {
        window.location.href = "http://localhost:3010/category/automotive";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/9652c1fa-3f69-498f-bb68-d7ada2f50fba")) {
        window.location.href = "http://localhost:3010/product/9652c1fa-3f69-498f-bb68-d7ada2f50fba";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_ef480a4f7aa84057b470399bc2dc0e
  // Safety: read
  // Source: http://localhost:3010/category/automotive
  navigator.modelContext.registerTool({
    name: "localhost_navigate_ef480a4f7aa84057b470399bc2dc0e",
    description: "Navigate from http://localhost:3010/category/automotive to http://localhost:3010/product/ef480a4f-7aa8-4057-b470-399bc2dc0e3b.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/automotive")) {
        window.location.href = "http://localhost:3010/category/automotive";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/ef480a4f-7aa8-4057-b470-399bc2dc0e3b")) {
        window.location.href = "http://localhost:3010/product/ef480a4f-7aa8-4057-b470-399bc2dc0e3b";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_5d9701b0ac7348c2848896f3b8e649
  // Safety: read
  // Source: http://localhost:3010/category/automotive
  navigator.modelContext.registerTool({
    name: "localhost_navigate_5d9701b0ac7348c2848896f3b8e649",
    description: "Navigate from http://localhost:3010/category/automotive to http://localhost:3010/product/5d9701b0-ac73-48c2-8488-96f3b8e649e9.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/automotive")) {
        window.location.href = "http://localhost:3010/category/automotive";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/5d9701b0-ac73-48c2-8488-96f3b8e649e9")) {
        window.location.href = "http://localhost:3010/product/5d9701b0-ac73-48c2-8488-96f3b8e649e9";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_194fb672fd9d4694bde0712ab093a9
  // Safety: read
  // Source: http://localhost:3010/category/automotive
  navigator.modelContext.registerTool({
    name: "localhost_navigate_194fb672fd9d4694bde0712ab093a9",
    description: "Navigate from http://localhost:3010/category/automotive to http://localhost:3010/product/194fb672-fd9d-4694-bde0-712ab093a944.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/automotive")) {
        window.location.href = "http://localhost:3010/category/automotive";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/194fb672-fd9d-4694-bde0-712ab093a944")) {
        window.location.href = "http://localhost:3010/product/194fb672-fd9d-4694-bde0-712ab093a944";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_825f89857981463bb5ed59e3e05718
  // Safety: read
  // Source: http://localhost:3010/category/beauty
  navigator.modelContext.registerTool({
    name: "localhost_navigate_825f89857981463bb5ed59e3e05718",
    description: "Navigate from http://localhost:3010/category/beauty to http://localhost:3010/product/825f8985-7981-463b-b5ed-59e3e0571899.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/beauty")) {
        window.location.href = "http://localhost:3010/category/beauty";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/825f8985-7981-463b-b5ed-59e3e0571899")) {
        window.location.href = "http://localhost:3010/product/825f8985-7981-463b-b5ed-59e3e0571899";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_bacb5f18b4184faba4c75b4ae02755
  // Safety: read
  // Source: http://localhost:3010/category/beauty
  navigator.modelContext.registerTool({
    name: "localhost_navigate_bacb5f18b4184faba4c75b4ae02755",
    description: "Navigate from http://localhost:3010/category/beauty to http://localhost:3010/product/bacb5f18-b418-4fab-a4c7-5b4ae02755ac.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/beauty")) {
        window.location.href = "http://localhost:3010/category/beauty";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/bacb5f18-b418-4fab-a4c7-5b4ae02755ac")) {
        window.location.href = "http://localhost:3010/product/bacb5f18-b418-4fab-a4c7-5b4ae02755ac";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_210775d4300846ffa2010ce0bba44a
  // Safety: read
  // Source: http://localhost:3010/category/beauty
  navigator.modelContext.registerTool({
    name: "localhost_navigate_210775d4300846ffa2010ce0bba44a",
    description: "Navigate from http://localhost:3010/category/beauty to http://localhost:3010/product/210775d4-3008-46ff-a201-0ce0bba44a63.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/beauty")) {
        window.location.href = "http://localhost:3010/category/beauty";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/210775d4-3008-46ff-a201-0ce0bba44a63")) {
        window.location.href = "http://localhost:3010/product/210775d4-3008-46ff-a201-0ce0bba44a63";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_a394cf96e5ab45a7a843e784a22fa3
  // Safety: read
  // Source: http://localhost:3010/category/toys
  navigator.modelContext.registerTool({
    name: "localhost_navigate_a394cf96e5ab45a7a843e784a22fa3",
    description: "Navigate from http://localhost:3010/category/toys to http://localhost:3010/product/a394cf96-e5ab-45a7-a843-e784a22fa390.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/toys")) {
        window.location.href = "http://localhost:3010/category/toys";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/a394cf96-e5ab-45a7-a843-e784a22fa390")) {
        window.location.href = "http://localhost:3010/product/a394cf96-e5ab-45a7-a843-e784a22fa390";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_b0212657537b486a93785e026c4f6f
  // Safety: read
  // Source: http://localhost:3010/category/toys
  navigator.modelContext.registerTool({
    name: "localhost_navigate_b0212657537b486a93785e026c4f6f",
    description: "Navigate from http://localhost:3010/category/toys to http://localhost:3010/product/b0212657-537b-486a-9378-5e026c4f6ffd.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/toys")) {
        window.location.href = "http://localhost:3010/category/toys";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/b0212657-537b-486a-9378-5e026c4f6ffd")) {
        window.location.href = "http://localhost:3010/product/b0212657-537b-486a-9378-5e026c4f6ffd";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_a42a8e33a5b5404ea530dfcab7cb39
  // Safety: read
  // Source: http://localhost:3010/category/toys
  navigator.modelContext.registerTool({
    name: "localhost_navigate_a42a8e33a5b5404ea530dfcab7cb39",
    description: "Navigate from http://localhost:3010/category/toys to http://localhost:3010/product/a42a8e33-a5b5-404e-a530-dfcab7cb393e.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/toys")) {
        window.location.href = "http://localhost:3010/category/toys";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/a42a8e33-a5b5-404e-a530-dfcab7cb393e")) {
        window.location.href = "http://localhost:3010/product/a42a8e33-a5b5-404e-a530-dfcab7cb393e";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  // Tool: localhost_navigate_5c1a362e28cc4868b8f02e148b3966
  // Safety: read
  // Source: http://localhost:3010/category/toys
  navigator.modelContext.registerTool({
    name: "localhost_navigate_5c1a362e28cc4868b8f02e148b3966",
    description: "Navigate from http://localhost:3010/category/toys to http://localhost:3010/product/5c1a362e-28cc-4868-b8f0-2e148b39667a.",
    inputSchema: {
      "type": "object",
      "properties": {}
    },
    annotations: {"readOnlyHint":"true"},
    execute: async (_params: Record<string, unknown>) => {
      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/category/toys")) {
        window.location.href = "http://localhost:3010/category/toys";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Ensure we're on the right page
      if (!window.location.pathname.startsWith("/product/5c1a362e-28cc-4868-b8f0-2e148b39667a")) {
        window.location.href = "http://localhost:3010/product/5c1a362e-28cc-4868-b8f0-2e148b39667a";
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      return { content: [{ type: "text", text: "Done" }] };
    },
  });

  console.log("[WebMCP] Registered 51 tools");
}

// Initialize when DOM is ready
if (typeof window !== 'undefined') {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initWebMCPTools);
  } else {
    initWebMCPTools();
  }
}
