import type { RolePlayScenario } from './buddyScenarios';

export const SCENARIOS: RolePlayScenario[] = [
  {
    id: 'greeting-classmate',
    category: 'greeting',
    title: 'Greeting a Classmate',
    description: 'Practice saying hi to someone you know from class',
    context: 'You see a classmate from your math class in the hallway. You\'ve worked together on a project before, but you don\'t usually talk outside of class.',
    yourRole: 'You',
    otherRole: 'Classmate (Alex)',
    goal: 'Start a brief, friendly conversation',
    difficulty: 'easy',
    skillsTaught: ['Initiating conversation', 'Small talk', 'Reading social cues'],
    safetyBoundaries: [
      'Keep it brief and casual',
      'It\'s okay if they seem busy',
      'No pressure to become best friends',
    ],
    reflectionPrompts: [
      'How did it feel to start the conversation?',
      'What went well?',
      'What would you do differently next time?',
    ],
  },
  {
    id: 'joining-conversation',
    category: 'group',
    title: 'Joining a Group Conversation',
    description: 'Learn when and how to join people who are already talking',
    context: 'It\'s lunch time. You see a group of 3-4 people you know talking and laughing near the cafeteria. You want to join them.',
    yourRole: 'You',
    otherRole: 'Group of friends',
    goal: 'Join the conversation naturally without interrupting',
    difficulty: 'medium',
    skillsTaught: ['Timing', 'Group dynamics', 'Non-verbal cues', 'Finding entry points'],
    safetyBoundaries: [
      'Wait for a natural pause',
      'It\'s okay to just listen at first',
      'If they seem deep in conversation, it\'s fine to wait or come back later',
    ],
    reflectionPrompts: [
      'How did you know when to join in?',
      'What signals did you notice from the group?',
      'Did you feel welcomed? Why or why not?',
    ],
  },
  {
    id: 'misunderstanding-friend',
    category: 'conflict',
    title: 'Clearing Up a Misunderstanding',
    description: 'Practice addressing when a friend seems upset with you',
    context: 'Your friend has been acting distant for the past few days. They\'ve been short with you and haven\'t responded to your messages like they usually do. You\'re not sure what happened.',
    yourRole: 'You',
    otherRole: 'Friend (Jordan)',
    goal: 'Gently ask what\'s wrong and listen to their perspective',
    difficulty: 'hard',
    skillsTaught: ['Conflict resolution', 'Active listening', 'Empathy', 'Taking responsibility'],
    safetyBoundaries: [
      'Stay calm and non-defensive',
      'Listen more than you explain',
      'It\'s okay to say "I didn\'t realize that hurt you"',
      'Not all conflicts resolve immediately',
    ],
    reflectionPrompts: [
      'How did you approach the situation?',
      'What did you learn about your friend\'s perspective?',
      'What could help prevent this in the future?',
    ],
  },
  {
    id: 'sharing-interest',
    category: 'conversation',
    title: 'Sharing Your Interest',
    description: 'Practice talking about something you care about without over-sharing',
    context: 'Someone asks you about your weekend. You spent most of it doing something you really enjoy (gaming, reading, a hobby, etc.). You want to share but also keep them engaged.',
    yourRole: 'You',
    otherRole: 'Acquaintance (Sam)',
    goal: 'Share your interest while reading their engagement level',
    difficulty: 'medium',
    skillsTaught: ['Balanced conversation', 'Reading interest cues', 'Asking follow-up questions'],
    safetyBoundaries: [
      'Watch for signs they\'re interested or losing interest',
      'Pause to let them respond',
      'Ask about their weekend too',
      'It\'s okay if they don\'t share your interest',
    ],
    reflectionPrompts: [
      'Did they seem interested in what you shared?',
      'How did you balance talking and listening?',
      'What cues did you notice about their engagement?',
    ],
  },
  {
    id: 'online-group-chat',
    category: 'online',
    title: 'Joining an Online Group Chat',
    description: 'Practice entering an ongoing group chat conversation',
    context: 'You\'re in a Discord/group chat with people from school. There\'s an active conversation happening about weekend plans. You want to join in.',
    yourRole: 'You',
    otherRole: 'Group chat members',
    goal: 'Join the conversation naturally in a text-based setting',
    difficulty: 'easy',
    skillsTaught: ['Online communication', 'Timing in text', 'Group chat etiquette'],
    safetyBoundaries: [
      'Read the last few messages first',
      'It\'s okay to just react with an emoji at first',
      'Don\'t feel pressure to respond to everything',
      'Online conversations move fast - that\'s normal',
    ],
    reflectionPrompts: [
      'How is online conversation different from in-person?',
      'What made it easier or harder?',
      'Did you feel included?',
    ],
  },
  {
    id: 'asking-teacher-help',
    category: 'school',
    title: 'Asking a Teacher for Help',
    description: 'Practice requesting clarification or help from a teacher',
    context: 'You\'re confused about a math homework problem. The teacher is at their desk after class, and a few other students are also asking questions.',
    yourRole: 'You',
    otherRole: 'Teacher (Mrs. Johnson)',
    goal: 'Politely ask for help and clarify what you don\'t understand',
    difficulty: 'easy',
    skillsTaught: ['Self-advocacy', 'Asking clarifying questions', 'Turn-taking', 'Respect for authority'],
    safetyBoundaries: [
      'Wait for the teacher to finish with other students',
      'It\'s okay to admit you don\'t understand',
      'Teachers want to help - it\'s their job',
      'If they\'re busy, ask when a good time would be',
    ],
    reflectionPrompts: [
      'How did it feel to ask for help?',
      'Did you get the information you needed?',
      'What would you do differently next time?',
    ],
  },
  {
    id: 'group-project-collaboration',
    category: 'school',
    title: 'Working on a Group Project',
    description: 'Navigate group dynamics and contribute to a shared task',
    context: 'You\'re assigned to a group of 4 for a history project. The group is meeting to divide up the work. Everyone has different ideas about how to approach it.',
    yourRole: 'You',
    otherRole: 'Group members (Emma, Jake, Sophia)',
    goal: 'Contribute ideas, negotiate roles, and find common ground',
    difficulty: 'hard',
    skillsTaught: ['Collaboration', 'Compromise', 'Sharing ideas', 'Handling disagreements', 'Division of labor'],
    safetyBoundaries: [
      'Everyone\'s ideas have value',
      'It\'s okay to disagree respectfully',
      'You don\'t have to do everything - share the work',
      'If someone dominates, it\'s okay to speak up',
    ],
    reflectionPrompts: [
      'Did you feel heard by the group?',
      'How did you handle disagreements?',
      'What role works best for you in groups?',
    ],
  },
  {
    id: 'sibling-disagreement',
    category: 'family',
    title: 'Resolving a Disagreement with a Sibling',
    description: 'Practice conflict resolution with family members',
    context: 'Your sibling borrowed your gaming headset without asking and now it\'s broken. You\'re upset, but you want to resolve this without yelling.',
    yourRole: 'You',
    otherRole: 'Sibling (Alex)',
    goal: 'Express how you feel and find a fair solution',
    difficulty: 'medium',
    skillsTaught: ['Conflict resolution', 'Expressing emotions calmly', 'Problem-solving', 'Empathy'],
    safetyBoundaries: [
      'Use "I feel" statements, not accusations',
      'Listen to their side of the story',
      'It\'s okay to take a break if you get too upset',
      'Parents can help mediate if needed',
    ],
    reflectionPrompts: [
      'Did you stay calm during the conversation?',
      'Did you understand their perspective?',
      'What solution feels fair to both of you?',
    ],
  },
  {
    id: 'asking-parent-permission',
    category: 'family',
    title: 'Asking Parents for Permission',
    description: 'Practice respectful negotiation with parents',
    context: 'Your friends are going to the mall on Saturday and you want to go too. You need to ask your parents, but they usually worry about you being out without them.',
    yourRole: 'You',
    otherRole: 'Parent',
    goal: 'Present your request maturely and address their concerns',
    difficulty: 'medium',
    skillsTaught: ['Self-advocacy', 'Anticipating concerns', 'Responsible planning', 'Negotiation'],
    safetyBoundaries: [
      'Choose a good time to ask (not when they\'re busy/stressed)',
      'Show you\'ve thought about safety and logistics',
      'Be prepared for "no" and handle it maturely',
      'Compromise is okay (shorter time, check-ins, etc.)',
    ],
    reflectionPrompts: [
      'Did you present your case clearly?',
      'How did you handle their concerns?',
      'Would you approach it differently next time?',
    ],
  },
  {
    id: 'gaming-chat-etiquette',
    category: 'online',
    title: 'Navigating Gaming Voice Chat',
    description: 'Practice online communication during multiplayer gaming',
    context: 'You\'re playing a team-based game with voice chat. One teammate is getting frustrated and blaming others for losses. The atmosphere is tense.',
    yourRole: 'You',
    otherRole: 'Gaming teammates',
    goal: 'Stay positive, communicate effectively, and handle toxic behavior',
    difficulty: 'medium',
    skillsTaught: ['Online communication', 'Teamwork', 'Handling conflict', 'Muting/reporting when necessary'],
    safetyBoundaries: [
      'You can mute toxic players - it\'s not rude',
      'Don\'t engage with people who are being mean',
      'It\'s just a game - your well-being matters more',
      'Report serious harassment to game moderators',
    ],
    reflectionPrompts: [
      'How did you handle the frustration?',
      'When is it okay to mute someone?',
      'What makes gaming communication different?',
    ],
  },
  {
    id: 'handling-online-trolls',
    category: 'online',
    title: 'Responding to Online Trolling',
    description: 'Learn when to engage, ignore, or report online negativity',
    context: 'You posted a video of yourself playing guitar on social media. Someone left a mean comment saying you sound terrible. Other people have started arguing with them in the comments.',
    yourRole: 'You',
    otherRole: 'Various commenters',
    goal: 'Decide how to respond (or not respond) appropriately',
    difficulty: 'hard',
    skillsTaught: ['Emotional regulation', 'Online safety', 'Choosing battles', 'Reporting vs. engaging'],
    safetyBoundaries: [
      'You don\'t owe trolls a response',
      'Block/report is always an option',
      'Don\'t let strangers\' opinions define your worth',
      'Talk to a trusted adult if it\'s bothering you',
    ],
    reflectionPrompts: [
      'How did the comment make you feel?',
      'What response (or non-response) feels right?',
      'What would you tell a friend in this situation?',
    ],
  },
  {
    id: 'explaining-autism-to-peer',
    category: 'self-advocacy',
    title: 'Explaining Your Needs to a Peer',
    description: 'Practice self-advocacy and explaining autism/ADHD to friends',
    context: 'A friend invited you to a loud, crowded party. You want to go but you\'re worried about sensory overload. You\'re thinking about explaining your needs to them.',
    yourRole: 'You',
    otherRole: 'Friend (Taylor)',
    goal: 'Explain your sensory needs without oversharing or feeling ashamed',
    difficulty: 'hard',
    skillsTaught: ['Self-advocacy', 'Disclosure decisions', 'Setting boundaries', 'Educating others'],
    safetyBoundaries: [
      'You decide what to share and with whom',
      'It\'s okay to say "I need..." without explaining your diagnosis',
      'True friends will respect your needs',
      'You can suggest alternatives (quieter hangout, shorter stay)',
    ],
    reflectionPrompts: [
      'Did you feel comfortable sharing?',
      'How did they respond?',
      'What level of detail feels right for you?',
    ],
  },
  {
    id: 'requesting-accommodations',
    category: 'self-advocacy',
    title: 'Requesting School Accommodations',
    description: 'Practice asking for help or accommodations you need',
    context: 'You have an IEP/504 plan that allows extra time on tests, but your new teacher doesn\'t seem to know about it. You need to advocate for yourself.',
    yourRole: 'You',
    otherRole: 'Teacher (Mr. Rodriguez)',
    goal: 'Politely remind the teacher of your accommodations',
    difficulty: 'medium',
    skillsTaught: ['Self-advocacy', 'Knowing your rights', 'Professional communication'],
    safetyBoundaries: [
      'Your accommodations are legal and fair',
      'You have a right to them - don\'t feel guilty',
      'Be polite but firm',
      'If the teacher refuses, talk to your case manager',
    ],
    reflectionPrompts: [
      'How did it feel to advocate for yourself?',
      'Did the teacher respond positively?',
      'What will you do if this happens again?',
    ],
  },
  {
    id: 'peer-pressure-scenario',
    category: 'conflict',
    title: 'Handling Peer Pressure',
    description: 'Practice saying no to things that make you uncomfortable',
    context: 'Some classmates are skipping last period to go get food off-campus. They\'re trying to convince you to come along, but you don\'t want to get in trouble.',
    yourRole: 'You',
    otherRole: 'Classmates (Chris and Sam)',
    goal: 'Say no while maintaining friendships',
    difficulty: 'hard',
    skillsTaught: ['Assertiveness', 'Saying no', 'Resisting peer pressure', 'Values alignment'],
    safetyBoundaries: [
      'You can say no without giving a long explanation',
      'Real friends won\'t pressure you',
      'It\'s okay to make different choices',
      'You can suggest alternative plans later',
    ],
    reflectionPrompts: [
      'How did it feel to say no?',
      'Did they respect your decision?',
      'What strategies helped you stay firm?',
    ],
  },
  {
    id: 'making-small-talk',
    category: 'conversation',
    title: 'Small Talk at a Social Event',
    description: 'Practice casual conversation with acquaintances',
    context: 'You\'re at a school event (game, dance, etc.) and standing near people you sort of know but haven\'t talked to much. There\'s an awkward silence.',
    yourRole: 'You',
    otherRole: 'Acquaintances (Morgan and Jamie)',
    goal: 'Start or join casual conversation without overthinking',
    difficulty: 'medium',
    skillsTaught: ['Small talk', 'Conversation starters', 'Reading the room', 'Casual social interaction'],
    safetyBoundaries: [
      'Small talk doesn\'t have to be deep or meaningful',
      'It\'s okay if the conversation fizzles out',
      'Commenting on the shared experience is always safe',
      'You can excuse yourself if it\'s too uncomfortable',
    ],
    reflectionPrompts: [
      'What topics felt natural to discuss?',
      'Did you feel pressure to keep talking?',
      'When is it okay to end a conversation?',
    ],
  },
  {
    id: 'receiving-criticism',
    category: 'conversation',
    title: 'Receiving Constructive Criticism',
    description: 'Practice accepting feedback without getting defensive',
    context: 'A teacher returns your essay with a lot of corrections and suggestions. You worked really hard on it and feel disappointed by the feedback.',
    yourRole: 'You',
    otherRole: 'Teacher',
    goal: 'Listen to feedback, ask questions, and use it to improve',
    difficulty: 'medium',
    skillsTaught: ['Accepting feedback', 'Growth mindset', 'Emotional regulation', 'Asking for clarification'],
    safetyBoundaries: [
      'Feedback is about your work, not your worth',
      'It\'s okay to feel disappointed',
      'Asking "how can I improve?" shows maturity',
      'You can take time to process before revising',
    ],
    reflectionPrompts: [
      'How did you initially feel about the feedback?',
      'What specific improvements can you make?',
      'How do you handle criticism in general?',
    ],
  },
  {
    id: 'ending-toxic-friendship',
    category: 'conflict',
    title: 'Setting Boundaries with a Friend',
    description: 'Practice recognizing and addressing unhealthy friendships',
    context: 'A friend has been making you feel bad about yourself lately - they put down your interests, make fun of you in front of others, and only hang out when they need something.',
    yourRole: 'You',
    otherRole: 'Friend (Casey)',
    goal: 'Set boundaries or end the friendship if needed',
    difficulty: 'hard',
    skillsTaught: ['Boundary-setting', 'Recognizing unhealthy relationships', 'Self-respect', 'Difficult conversations'],
    safetyBoundaries: [
      'You deserve friends who treat you well',
      'It\'s okay to outgrow friendships',
      'You can start with a conversation before ending it',
      'Talk to a trusted adult if you need support',
    ],
    reflectionPrompts: [
      'What behaviors crossed your boundaries?',
      'How did you communicate your feelings?',
      'What kind of friendships do you want?',
    ],
  },
  {
    id: 'introducing-yourself-new-class',
    category: 'greeting',
    title: 'Introducing Yourself in a New Class',
    description: 'Practice self-introduction when starting fresh',
    context: 'It\'s the first day of a new semester elective. The teacher asks everyone to briefly introduce themselves (name, grade, why you took this class).',
    yourRole: 'You',
    otherRole: 'Class and Teacher',
    goal: 'Give a brief, confident self-introduction',
    difficulty: 'easy',
    skillsTaught: ['Self-presentation', 'Public speaking basics', 'Concise communication'],
    safetyBoundaries: [
      'Keep it brief (30 seconds max)',
      'You don\'t have to be funny or impressive',
      'It\'s okay to be nervous - everyone else is too',
      'Eye contact with the teacher is easier than scanning the whole class',
    ],
    reflectionPrompts: [
      'What did you choose to share about yourself?',
      'How did it feel to speak in front of the class?',
      'What would you add or change next time?',
    ],
  },
  {
    id: 'study-group-invitation',
    category: 'conversation',
    title: 'Inviting Someone to Study Together',
    description: 'Practice initiating casual academic collaboration',
    context: 'You and another student both did well on the last test. You\'re thinking about asking them to study together for the next one.',
    yourRole: 'You',
    otherRole: 'Classmate (River)',
    goal: 'Extend a study invitation without being awkward',
    difficulty: 'easy',
    skillsTaught: ['Initiating plans', 'Academic collaboration', 'Low-pressure invitations'],
    safetyBoundaries: [
      'If they say no, it\'s not personal',
      'Suggest a specific time/place (makes it easier)',
      'You can study alone if they\'re not interested',
      'Academic collaboration is a low-pressure way to build friendships',
    ],
    reflectionPrompts: [
      'How did you phrase the invitation?',
      'Did you feel anxious beforehand?',
      'What would you do differently?',
    ],
  },
  {
    id: 'party-sensory-overload',
    category: 'group',
    title: 'Managing Sensory Overload at a Party',
    description: 'Practice self-regulation and knowing when to take breaks',
    context: 'You\'re at a friend\'s birthday party. It\'s louder and more crowded than you expected. You\'re starting to feel overwhelmed but don\'t want to seem rude by leaving.',
    yourRole: 'You',
    otherRole: 'Friend (host) and other partygoers',
    goal: 'Recognize your limits and take care of yourself without guilt',
    difficulty: 'medium',
    skillsTaught: ['Self-awareness', 'Sensory regulation', 'Polite exit strategies', 'Self-care'],
    safetyBoundaries: [
      'Taking a break outside is okay',
      'You can leave early if you need to',
      'Explain briefly or not at all - your choice',
      'Bringing headphones/fidgets for breaks is smart planning',
    ],
    reflectionPrompts: [
      'What sensory inputs were overwhelming?',
      'What strategies helped you cope?',
      'How can you prepare better for next time?',
    ],
  },
];
