"""Frozen canonical runtime schema and legacy additive upgrades."""
from alembic import op
import sqlalchemy as sa
revision="20260821_01";down_revision="0731d6d83b4a";branch_labels=None;depends_on=None
def tables():return set(sa.inspect(op.get_bind()).get_table_names())
def create(name,*columns,**kwargs):
 if name not in tables():op.create_table(name,*columns,**kwargs)
def index(name,table,columns,unique=False):
 if name not in {i["name"] for i in sa.inspect(op.get_bind()).get_indexes(table)}:op.create_index(name,table,columns,unique=unique)
def upgrade():
 create("evidence_records",sa.Column("evidence_id",sa.String(36),primary_key=True),sa.Column("case_id",sa.String(64),nullable=False),sa.Column("display_filename",sa.String(255),nullable=False),sa.Column("original_path",sa.String(600),nullable=False),sa.Column("byte_length",sa.Integer,nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("declared_mime",sa.String(255)),sa.Column("detected_mime",sa.String(120),nullable=False),sa.Column("detected_type",sa.String(20),nullable=False),sa.Column("imported_at",sa.DateTime,nullable=False),sa.Column("source_label",sa.String(200),nullable=False),sa.Column("received_from",sa.String(500)),sa.Column("notes",sa.String(4000)),sa.Column("evidence_date",sa.DateTime),sa.Column("status",sa.String(32),nullable=False),sa.Column("error_code",sa.String(64)),sa.Column("error_message",sa.String(500)),sa.Column("same_content_as",sa.String(36)),sa.Column("created_at",sa.DateTime,nullable=False),sa.Column("updated_at",sa.DateTime,nullable=False),sa.CheckConstraint("byte_length >= 0"))
 create("extraction_attempts",sa.Column("attempt_id",sa.String(36),primary_key=True),sa.Column("evidence_id",sa.String(36),sa.ForeignKey("evidence_records.evidence_id"),nullable=False),sa.Column("extractor_name",sa.String(100),nullable=False),sa.Column("extractor_version",sa.String(50),nullable=False),sa.Column("started_at",sa.DateTime,nullable=False),sa.Column("completed_at",sa.DateTime),sa.Column("status",sa.String(32),nullable=False),sa.Column("page_count",sa.Integer),sa.Column("text_path",sa.String(600)),sa.Column("text_sha256",sa.String(64)),sa.Column("derivative_path",sa.String(600)),sa.Column("error_code",sa.String(64)),sa.Column("error_message",sa.String(500)))
 if "text_sha256" not in {c["name"] for c in sa.inspect(op.get_bind()).get_columns("extraction_attempts")}:op.add_column("extraction_attempts",sa.Column("text_sha256",sa.String(64)))
 create("evidence_chunks",sa.Column("chunk_id",sa.String(64),primary_key=True),sa.Column("case_id",sa.String(64),nullable=False),sa.Column("evidence_id",sa.String(36),sa.ForeignKey("evidence_records.evidence_id"),nullable=False),sa.Column("extraction_attempt_id",sa.String(36),sa.ForeignKey("extraction_attempts.attempt_id"),nullable=False),sa.Column("ordinal",sa.Integer,nullable=False),sa.Column("text",sa.String,nullable=False),sa.Column("text_sha256",sa.String(64),nullable=False),sa.Column("paragraph_index",sa.Integer),sa.Column("page_number",sa.Integer),sa.Column("char_start",sa.Integer,nullable=False),sa.Column("char_end",sa.Integer,nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime,nullable=False),sa.CheckConstraint("ordinal >= 0"),sa.CheckConstraint("char_start >= 0"),sa.CheckConstraint("char_end >= char_start"))
 create("legal_packs",sa.Column("pack_id",sa.String(80),primary_key=True),sa.Column("pack_key",sa.String(80),nullable=False),sa.Column("jurisdiction",sa.String(100),nullable=False),sa.Column("matter_type",sa.String(120),nullable=False),sa.Column("version",sa.String(30),nullable=False),sa.Column("as_of",sa.String(30),nullable=False),sa.Column("retrieved_at",sa.DateTime,nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("approval_status",sa.String(40),nullable=False),sa.Column("snapshot_path",sa.String(600),nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("installed_at",sa.DateTime,nullable=False),sa.UniqueConstraint("pack_key","version",name="uq_legal_pack_version"))
 create("legal_sources",sa.Column("source_id",sa.String(100),primary_key=True),sa.Column("pack_id",sa.String(80),sa.ForeignKey("legal_packs.pack_id"),nullable=False),sa.Column("ordinal",sa.Integer,nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("canonical_url",sa.String(600),nullable=False),sa.Column("official",sa.Boolean,nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("locator",sa.String(100),nullable=False),sa.Column("excerpt",sa.String,nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("retrieved_at",sa.DateTime,nullable=False))
 create("legal_rule_elements",sa.Column("element_id",sa.String(120),primary_key=True),sa.Column("source_id",sa.String(100),sa.ForeignKey("legal_sources.source_id"),nullable=False),sa.Column("pack_id",sa.String(80),sa.ForeignKey("legal_packs.pack_id"),nullable=False),sa.Column("ordinal",sa.Integer,nullable=False),sa.Column("authority_text",sa.String,nullable=False),sa.Column("applicability",sa.String(500),nullable=False),sa.Column("status",sa.String(40),nullable=False))
 create("issue_analysis_runs",sa.Column("run_id",sa.String(36),primary_key=True),sa.Column("case_id",sa.String(64),nullable=False),sa.Column("pack_id",sa.String(80),nullable=False),sa.Column("engine_id",sa.String(80),nullable=False),sa.Column("ruleset_id",sa.String(80),nullable=False),sa.Column("ruleset_status",sa.String(50),nullable=False),sa.Column("ruleset_sha256",sa.String(64),nullable=False),sa.Column("input_sha256",sa.String(64),nullable=False),sa.Column("input_manifest_json",sa.String,nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime,nullable=False),sa.Column("completed_at",sa.DateTime))
 create("issue_findings",sa.Column("finding_id",sa.String(36),primary_key=True),sa.Column("run_id",sa.String(36),sa.ForeignKey("issue_analysis_runs.run_id"),nullable=False),sa.Column("case_id",sa.String(64),nullable=False),sa.Column("issue_key",sa.String(80),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("label",sa.String(30),nullable=False),sa.Column("rationale",sa.String(1000),nullable=False),sa.Column("confidence",sa.String(20),nullable=False),sa.Column("source_id",sa.String(100),nullable=False),sa.Column("element_id",sa.String(120),nullable=False),sa.Column("created_at",sa.DateTime,nullable=False))
 create("finding_citations",sa.Column("citation_id",sa.String(36),primary_key=True),sa.Column("finding_id",sa.String(36),sa.ForeignKey("issue_findings.finding_id"),nullable=False),sa.Column("kind",sa.String(20),nullable=False),sa.Column("chunk_id",sa.String(64)),sa.Column("evidence_id",sa.String(36)),sa.Column("original_filename",sa.String(255)),sa.Column("provenance",sa.String(500)),sa.Column("imported_at",sa.DateTime),sa.Column("quote",sa.String,nullable=False),sa.Column("ordinal",sa.Integer),sa.Column("page_number",sa.Integer),sa.Column("paragraph_index",sa.Integer),sa.Column("char_start",sa.Integer),sa.Column("char_end",sa.Integer),sa.Column("source_id",sa.String(100)),sa.Column("locator",sa.String(100)),sa.Column("authority_title",sa.String(300)),sa.Column("canonical_url",sa.String(600)),sa.Column("retrieved_at",sa.DateTime),sa.Column("as_of",sa.String(50)),sa.Column("source_status",sa.String(40)),sa.Column("approval_status",sa.String(40)),sa.Column("text_sha256",sa.String(64),nullable=False))
 create("finding_missing_facts",sa.Column("missing_id",sa.String(36),primary_key=True),sa.Column("finding_id",sa.String(36),sa.ForeignKey("issue_findings.finding_id"),nullable=False),sa.Column("fact_key",sa.String(100),nullable=False),sa.Column("description",sa.String(500),nullable=False))
 create("finding_qualifications",sa.Column("qualification_id",sa.String(36),primary_key=True),sa.Column("finding_id",sa.String(36),sa.ForeignKey("issue_findings.finding_id"),nullable=False),sa.Column("code",sa.String(100),nullable=False),sa.Column("description",sa.String(700),nullable=False))
 create("finding_dispositions",sa.Column("disposition_id",sa.String(36),primary_key=True),sa.Column("finding_id",sa.String(36),sa.ForeignKey("issue_findings.finding_id"),nullable=False),sa.Column("version",sa.Integer,nullable=False),sa.Column("value",sa.String(30),nullable=False),sa.Column("note",sa.String(1000)),sa.Column("created_at",sa.DateTime,nullable=False),sa.UniqueConstraint("finding_id","version",name="uq_finding_disposition_version"))
 specs=(("ix_evidence_records_case_id","evidence_records",["case_id"],0),("ix_evidence_records_same_content_as","evidence_records",["same_content_as"],0),("ix_evidence_case_imported","evidence_records",["case_id","imported_at"],0),("ix_evidence_sha256","evidence_records",["sha256"],0),("ix_extraction_attempts_evidence_id","extraction_attempts",["evidence_id"],0),("ix_attempt_evidence_started","extraction_attempts",["evidence_id","started_at"],0),("ix_evidence_chunks_case_id","evidence_chunks",["case_id"],0),("ix_evidence_chunks_evidence_id","evidence_chunks",["evidence_id"],0),("ix_chunk_attempt","evidence_chunks",["extraction_attempt_id"],0),("ix_chunk_text_sha256","evidence_chunks",["text_sha256"],0),("ix_chunk_case_evidence_ordinal","evidence_chunks",["case_id","evidence_id","ordinal"],1),("ix_legal_packs_pack_key","legal_packs",["pack_key"],0),("ix_legal_sources_pack_id","legal_sources",["pack_id"],0),("ix_legal_source_pack","legal_sources",["pack_id","ordinal"],0),("ix_legal_rule_elements_source_id","legal_rule_elements",["source_id"],0),("ix_legal_rule_elements_pack_id","legal_rule_elements",["pack_id"],0),("ix_issue_analysis_runs_case_id","issue_analysis_runs",["case_id"],0),("ix_issue_run_case_created","issue_analysis_runs",["case_id","created_at"],0),("ix_issue_findings_run_id","issue_findings",["run_id"],0),("ix_issue_findings_case_id","issue_findings",["case_id"],0),("ix_finding_case_run","issue_findings",["case_id","run_id"],0),("ix_finding_citations_finding_id","finding_citations",["finding_id"],0),("ix_finding_missing_facts_finding_id","finding_missing_facts",["finding_id"],0),("ix_finding_qualifications_finding_id","finding_qualifications",["finding_id"],0),("ix_finding_dispositions_finding_id","finding_dispositions",["finding_id"],0),("uq_finding_disposition_version_idx","finding_dispositions",["finding_id","version"],1))
 for name,table,columns,unique in specs:index(name,table,columns,bool(unique))
def downgrade():pass
