import { useCallback, useEffect, useMemo, useState } from 'react';
import { LandingPage, createDefaultLandingContent } from '@vibetech/landing';

const content = createDefaultLandingContent({
  productName: 'Vibe-Tech',
  badge: 'Generated by @vibetech/factory:saas',
  title: 'Vibe-Tech Client Portal',
  subtitle:
    'This secure client portal is backed by the Vibe-Tech ecosystem, Fastify API, and entitlement-aware billing.',
  previewItems: [
    'Shared landing page',
    'Fastify API',
    'Protected pro route',
    'Workspace package wiring',
  ],
  featuresHeading: 'Factory defaults for monetized apps',
  featuresSubheading:
    'The generator starts with shared landing content, auth and entitlement package dependencies, and a first sign-in protected backend route.',
  features: [
    {
      title: 'Landing package',
      description: 'The frontend starts on the shared landing system instead of placeholder copy.',
    },
    {
      title: 'Login flow',
      description:
        'The generated app now includes a starter operator sign-in flow backed by @vibetech/auth.',
    },
    {
      title: 'Entitlement seam',
      description: 'The generated API includes a first plan-gated route under /api/pro.',
    },
  ],
  ctaHeading: 'Start from shared monetization primitives',
  ctaBody:
    'Replace the copy and plan details, then move straight into product-specific workflow work.',
  footerRight: 'Built with the VibeTech factory SaaS generator',
});

interface GeneratedAuthUser {
  email: string;
  fullName?: string;
}

export function App() {
  const pathname = window.location.pathname;
  const [authConfigured, setAuthConfigured] = useState(false);
  const [userEmail, setUserEmail] = useState('');
  const [password, setPassword] = useState('');
  const [currentUser, setCurrentUser] = useState<GeneratedAuthUser | null>(null);
  const [currentPlan, setCurrentPlan] = useState<string>('free');
  const [authMessage, setAuthMessage] = useState<string | null>(null);
  const [proMessage, setProMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState<'auth' | 'pro' | null>(null);
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [checkoutError, setCheckoutError] = useState<string | null>(null);
  
  const apiBase = useMemo(() => import.meta.env.VITE_API_BASE_URL ?? '', []);

  const refreshSession = useCallback(async () => {
    try {
      const response = await fetch(`${apiBase}/api/auth/me`, {
        credentials: 'include',
      });
      const body = (await response.json()) as {
        configured?: boolean;
        user?: GeneratedAuthUser | null;
      };

      setAuthConfigured(Boolean(body.configured));
      setCurrentUser(body.user ?? null);
      
      if (body.user) {
        // Fetch current plan status
        const proRes = await fetch(`${apiBase}/api/pro`, {
          credentials: 'include',
        });
        const proBody = await proRes.json();
        if (proRes.ok) {
          setCurrentPlan(proBody.plan || 'pro');
        } else {
          setCurrentPlan(proBody.plan || 'free');
        }
      } else {
        setCurrentPlan('free');
      }
    } catch {
      setAuthConfigured(false);
      setCurrentUser(null);
      setCurrentPlan('free');
    }
  }, [apiBase]);

  useEffect(() => {
    void refreshSession();
  }, [refreshSession]);

  async function signIn() {
    setLoading('auth');
    setAuthMessage(null);

    try {
      const response = await fetch(`${apiBase}/api/auth/login`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          email: userEmail,
          password,
        }),
      });
      const body = (await response.json()) as {
        user?: GeneratedAuthUser;
        error?: string;
        detail?: string;
      };

      if (!response.ok || !body.user) {
        throw new Error(body.detail ?? body.error ?? 'Unable to sign in');
      }

      setCurrentUser(body.user);
      setAuthConfigured(true);
      setPassword('');
      await refreshSession();
    } catch (requestError) {
      setAuthMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function signOut() {
    setLoading('auth');
    setAuthMessage(null);

    try {
      await fetch(`${apiBase}/api/auth/logout`, {
        method: 'POST',
        credentials: 'include',
      });
      setCurrentUser(null);
      await refreshSession();
    } catch (requestError) {
      setAuthMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function checkProRoute() {
    setLoading('pro');
    setProMessage(null);

    try {
      const response = await fetch(`${apiBase}/api/pro`, {
        credentials: 'include',
      });
      const body = (await response.json()) as {
        error?: string;
        feature?: string;
        plan?: string;
      };

      if (!response.ok || !body.feature) {
        throw new Error(body.error ?? 'Protected route check failed');
      }

      setProMessage(`Protected route is live for the ${body.plan} plan: ${body.feature}.`);
    } catch (requestError) {
      setProMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function startCheckout() {
    setCheckoutLoading(true);
    setCheckoutError(null);
    try {
      const response = await fetch(`${apiBase}/api/billing/demo-checkout`, {
        method: 'GET',
        credentials: 'include',
      });
      const body = await response.json();
      if (!response.ok || !body.url) {
        throw new Error(body.error ?? body.detail ?? 'Failed to generate checkout session');
      }
      window.location.href = body.url;
    } catch (err) {
      setCheckoutError(err instanceof Error ? err.message : String(err));
    } finally {
      setCheckoutLoading(false);
    }
  }

  if (pathname === '/billing/success') {
    return (
      <main
        style={{
          minHeight: '100vh',
          padding: '48px 24px',
          background: '#08111f',
          color: '#f5f7fb',
          fontFamily: 'Inter, system-ui, sans-serif',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <div
          style={{
            maxWidth: '500px',
            width: '100%',
            border: '1px solid rgba(148, 163, 184, 0.2)',
            borderRadius: '8px',
            background: 'rgba(15, 23, 42, 0.82)',
            padding: '32px',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>🎉</div>
          <h1 style={{ margin: '0 0 16px', fontSize: '32px' }}>Upgrade Successful!</h1>
          <p style={{ margin: '0 0 24px', color: '#b7c3d6', lineHeight: 1.6 }}>
            Thank you for upgrading to Vibe-Tech Pro. Your features are now active!
          </p>
          <button onClick={() => { window.location.href = '/'; }} style={{ width: '100%' }}>
            Go to Dashboard
          </button>
        </div>
      </main>
    );
  }

  if (pathname === '/billing/canceled') {
    return (
      <main
        style={{
          minHeight: '100vh',
          padding: '48px 24px',
          background: '#08111f',
          color: '#f5f7fb',
          fontFamily: 'Inter, system-ui, sans-serif',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <div
          style={{
            maxWidth: '500px',
            width: '100%',
            border: '1px solid rgba(148, 163, 184, 0.2)',
            borderRadius: '8px',
            background: 'rgba(15, 23, 42, 0.82)',
            padding: '32px',
            textAlign: 'center',
          }}
        >
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>❌</div>
          <h1 style={{ margin: '0 0 16px', fontSize: '32px' }}>Checkout Canceled</h1>
          <p style={{ margin: '0 0 24px', color: '#b7c3d6', lineHeight: 1.6 }}>
            The checkout session was canceled. No charges were made.
          </p>
          <button
            onClick={() => { window.location.href = '/'; }}
            className="secondary-button"
            style={{ width: '100%' }}
          >
            Return to Dashboard
          </button>
        </div>
      </main>
    );
  }

  if (pathname === '/terms') {
    return (
      <LegalPage
        title="Terms of service"
        intro="This SaaS app includes terms of service for Vibe-Tech (vibe-tech.org) client portal."
        sections={[
          {
            heading: 'Use of the service',
            body: 'Use the portal to manage your Vibe-Tech projects and assets. Product-specific commitments belong to Vibe-Tech.',
          },
          {
            heading: 'Billing',
            body: 'Paid access flows through the Vibe-Tech Stripe billing integration and configured plans.',
          },
          {
            heading: 'Acceptable use',
            body: 'Do not upload or submit unauthorized content to the Vibe-Tech client portal.',
          },
        ]}
      />
    );
  }

  if (pathname === '/privacy') {
    return (
      <LegalPage
        title="Privacy policy"
        intro="This privacy policy details how Vibe-Tech (vibe-tech.org) handles client data."
        sections={[
          {
            heading: 'Data collection',
            body: 'We store account, billing, and project-related data required to deliver Vibe-Tech services.',
          },
          {
            heading: 'Payments',
            body: 'All payments are handled securely via Stripe. Card details are never stored directly on Vibe-Tech servers.',
          },
          {
            heading: 'Analytics',
            body: 'Analytics help Vibe-Tech optimize client portal user experiences.',
          },
        ]}
      />
    );
  }

  return (
    <main>
      <LandingPage content={content} />
      <section className="page auth-grid">
        <article className="grid-card">
          <div className="eyebrow">Generated auth</div>
          <h2>
            {currentUser
              ? 'Signed in'
              : authConfigured
                ? 'Sign in required'
                : 'Auth not configured'}
          </h2>
          <p>
            {currentUser
              ? `Session active for ${currentUser.fullName ?? currentUser.email}.`
              : authConfigured
                ? 'Use the generated operator account to unlock the first pro route.'
                : 'Set AUTH_SECRET and the DEMO_USER_* values in .env before using the starter login flow.'}
          </p>
          {authMessage ? <p className="message">{authMessage}</p> : null}
        </article>
        <article className="grid-card auth-form-card">
          <div className="eyebrow">Operator account</div>
          {currentUser ? (
            <button
              className="secondary-button"
              onClick={() => void signOut()}
              disabled={loading !== null}
            >
              {loading === 'auth' ? 'Signing out...' : 'Sign out'}
            </button>
          ) : (
            <>
              <label className="field">
                Email
                <input
                  type="email"
                  value={userEmail}
                  onChange={(event) => setUserEmail(event.target.value)}
                  placeholder="owner@example.com"
                />
              </label>
              <label className="field">
                Password
                <input
                  type="password"
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                  placeholder="change-this-password"
                />
              </label>
              <button onClick={() => void signIn()} disabled={loading !== null}>
                {loading === 'auth' ? 'Signing in...' : 'Sign in for pro access'}
              </button>
            </>
          )}
        </article>
        <article className="grid-card">
          <div className="eyebrow">Pro route</div>
          <h2>/api/pro</h2>
          <p>
            The factory SaaS scaffold now includes a starter login flow and a sign-in protected
            entitlement route.
          </p>
          <button
            className="secondary-button"
            onClick={() => void checkProRoute()}
            disabled={loading !== null}
          >
            {loading === 'pro' ? 'Checking route...' : 'Check protected pro route'}
          </button>
          {proMessage ? (
            <div style={{ marginTop: '12px' }}>
              <p
                className="message"
                style={{
                  color: proMessage.toLowerCase().includes('upgrade') ? '#f59e0b' : '#22d3ee',
                  fontSize: '15px'
                }}
              >
                {proMessage}
              </p>
              {proMessage.toLowerCase().includes('upgrade') && currentPlan === 'free' ? (
                <button
                  onClick={() => void startCheckout()}
                  disabled={checkoutLoading}
                  style={{ marginTop: '12px', width: '100%' }}
                >
                  {checkoutLoading ? 'Redirecting to Stripe...' : 'Upgrade Now'}
                </button>
              ) : null}
            </div>
          ) : null}
        </article>
        {currentUser ? (
          <article className="grid-card">
            <div className="eyebrow">Subscription & Billing</div>
            <h2>
              Plan: <span style={{ color: currentPlan === 'pro' ? '#10b981' : '#f59e0b', textTransform: 'uppercase' }}>{currentPlan}</span>
            </h2>
            <p>
              {currentPlan === 'pro'
                ? 'Thank you for subscribing! You have full access to all Pro features, including the premium API routes.'
                : 'Upgrade your subscription to unlock pro route permissions, custom rewrite tools, and usage-metered AI assistant integrations.'}
            </p>
            {currentPlan === 'free' ? (
              <button
                onClick={() => void startCheckout()}
                disabled={checkoutLoading}
                style={{ width: '100%', marginTop: '8px' }}
              >
                {checkoutLoading ? 'Redirecting to Stripe...' : 'Upgrade to Pro'}
              </button>
            ) : (
              <div style={{ color: '#10b981', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px', marginTop: '12px' }}>
                ✓ Pro features activated
              </div>
            )}
            {checkoutError ? (
              <p className="message" style={{ color: '#ef4444', marginTop: '8px' }}>
                {checkoutError}
              </p>
            ) : null}
          </article>
        ) : null}
      </section>
      <section style={{ padding: '0 24px 48px' }}>
        <div
          style={{
            maxWidth: '1120px',
            margin: '0 auto',
            display: 'flex',
            justifyContent: 'space-between',
            gap: '12px',
            flexWrap: 'wrap',
            color: '#94a3b8',
          }}
        >
          <span>Powered by Vibe-Tech. Legal stubs at /terms and /privacy.</span>
          <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
            <a href="https://vibe-tech.org" target="_blank" rel="noopener noreferrer" style={{ color: '#67e8f9' }}>
              vibe-tech.org
            </a>
            <a href="/terms" style={{ color: '#67e8f9' }}>
              Terms
            </a>
            <a href="/privacy" style={{ color: '#67e8f9' }}>
              Privacy
            </a>
          </div>
        </div>
      </section>
    </main>
  );
}

function LegalPage({
  title,
  intro,
  sections,
}: {
  title: string;
  intro: string;
  sections: Array<{ heading: string; body: string }>;
}) {
  return (
    <main
      style={{
        minHeight: '100vh',
        padding: '48px 24px',
        background: '#08111f',
        color: '#f5f7fb',
        fontFamily: 'Inter, system-ui, sans-serif',
      }}
    >
      <div
        style={{
          maxWidth: '880px',
          margin: '0 auto',
          border: '1px solid rgba(148, 163, 184, 0.2)',
          borderRadius: '8px',
          background: 'rgba(15, 23, 42, 0.82)',
          padding: '24px',
        }}
      >
        <div
          style={{
            display: 'inline-block',
            marginBottom: '16px',
            padding: '6px 12px',
            borderRadius: '999px',
            background: 'rgba(14, 165, 233, 0.16)',
            color: '#67e8f9',
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
          }}
        >
          Factory legal stub
        </div>
        <h1 style={{ margin: '0 0 16px', fontSize: '40px', lineHeight: 1.1 }}>{title}</h1>
        <p style={{ margin: '0 0 24px', color: '#b7c3d6', lineHeight: 1.7 }}>{intro}</p>
        <div style={{ display: 'grid', gap: '20px' }}>
          {sections.map((section) => (
            <section key={section.heading}>
              <h2 style={{ margin: '0 0 8px', fontSize: '22px' }}>{section.heading}</h2>
              <p style={{ margin: 0, color: '#dbe4f2', lineHeight: 1.7 }}>{section.body}</p>
            </section>
          ))}
        </div>
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', marginTop: '24px' }}>
          <a href="/" style={{ color: '#67e8f9' }}>
            Back to app
          </a>
          <a href="/terms" style={{ color: '#67e8f9' }}>
            Terms
          </a>
          <a href="/privacy" style={{ color: '#67e8f9' }}>
            Privacy
          </a>
        </div>
      </div>
    </main>
  );
}
