import type { Database } from "better-sqlite3";

export function seedQuestsRegulation(db: Database) {
	const questStmt = db.prepare(
		`INSERT INTO quests (name, description, category, subcategory, icon, base_coins, bonus_coins, is_daily, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
	);

	const selfRegulationQuests = [
		// Phone/Screen
		[
			"Phone Away (Short Trip)",
			"Phone in pocket for <15 min car ride",
			"self_regulation",
			"phone",
			"📱",
			8,
			12,
			0,
			1,
		],
		[
			"Phone Away (Long Trip)",
			"Phone away for 30+ min car ride",
			"self_regulation",
			"phone",
			"🚗",
			15,
			20,
			0,
			2,
		],
		[
			"Phone Down at Dinner",
			"No phone during family dinner",
			"self_regulation",
			"phone",
			"🍽️",
			10,
			15,
			1,
			3,
		],
		[
			"Phone Charged in Spot",
			"Phone charging in designated spot overnight",
			"self_regulation",
			"phone",
			"🔌",
			8,
			12,
			1,
			4,
		],
		[
			"Screen Limit Respected",
			"Stopped when time was up, no arguing",
			"self_regulation",
			"phone",
			"⏱️",
			10,
			15,
			1,
			5,
		],
		[
			"Good Gaming Transition",
			"Switched off game without meltdown",
			"self_regulation",
			"phone",
			"🎮",
			15,
			20,
			0,
			6,
		],
		[
			"Accepted 'No' to Screen Time",
			"Handled denial gracefully",
			"self_regulation",
			"phone",
			"✋",
			10,
			15,
			0,
			7,
		],
		[
			"Chose Non-Screen Activity",
			"Picked reading, LEGO, outside, etc.",
			"self_regulation",
			"phone",
			"📚",
			10,
			15,
			0,
			8,
		],

		// Focus/Patience
		[
			"Waited Patiently",
			"Waited 5+ minutes without complaining",
			"self_regulation",
			"patience",
			"⏳",
			8,
			12,
			0,
			9,
		],
		[
			"Didn't Interrupt",
			"Let others finish speaking",
			"self_regulation",
			"patience",
			"🤐",
			8,
			12,
			0,
			10,
		],
		[
			"Focused Homework Time",
			"No distractions during homework",
			"self_regulation",
			"patience",
			"📝",
			15,
			20,
			1,
			11,
		],
		[
			"Did Boring Task",
			"Completed without complaining",
			"self_regulation",
			"patience",
			"😐",
			10,
			15,
			0,
			12,
		],
		[
			"Handled Plan Change",
			"Adapted when plans changed",
			"self_regulation",
			"patience",
			"🔄",
			15,
			20,
			0,
			13,
		],
		[
			"Accepted Correction",
			"Took feedback without arguing",
			"self_regulation",
			"patience",
			"👍",
			15,
			20,
			0,
			14,
		],
		[
			"Asked for Help",
			"Asked when stuck instead of giving up",
			"self_regulation",
			"patience",
			"🙋",
			10,
			15,
			0,
			15,
		],
		[
			"Tried Again After Failure",
			"Didn't give up, tried again",
			"self_regulation",
			"patience",
			"💪",
			15,
			20,
			0,
			16,
		],

		// Emotional
		[
			"Used Calming Strategy",
			"Deep breaths, walk away, etc.",
			"self_regulation",
			"emotional",
			"🧘",
			20,
			25,
			0,
			17,
		],
		[
			"Expressed Feelings with Words",
			"Said 'I'm frustrated' instead of acting out",
			"self_regulation",
			"emotional",
			"💬",
			15,
			20,
			0,
			18,
		],
		[
			"Recovered from Disappointment",
			"Bounced back quickly",
			"self_regulation",
			"emotional",
			"🌈",
			15,
			20,
			0,
			19,
		],
		[
			"Handled Losing Gracefully",
			"No rage quit or bad attitude",
			"self_regulation",
			"emotional",
			"🎯",
			15,
			20,
			0,
			20,
		],
		[
			"Named Own Emotions",
			"Recognized and stated how you feel",
			"self_regulation",
			"emotional",
			"🎭",
			10,
			15,
			0,
			21,
		],
		[
			"Apologized Sincerely",
			"Owned mistake and said sorry",
			"self_regulation",
			"emotional",
			"🙏",
			15,
			20,
			0,
			22,
		],
		[
			"Walked Away from Argument",
			"Chose to de-escalate",
			"self_regulation",
			"emotional",
			"🚶",
			15,
			20,
			0,
			23,
		],
	];

	selfRegulationQuests.forEach((q) => questStmt.run(...q));
	console.log("✅ Self-regulation quests created");
}
