import type { Database } from "better-sqlite3";

export function seedRewards(db: Database) {
	const rewardStmt = db.prepare(
		`INSERT INTO rewards (name, description, category, icon, cost, real_value, rarity, is_limited, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
	);

	const rewards = [
		// Robux
		[
			"400 Robux",
			"Starter pack for avatar items & game passes",
			"robux",
			"💚",
			500,
			"$4.99 value",
			"common",
			0,
			1,
		],
		[
			"800 Robux",
			"Popular pack for limited items & premium games",
			"robux",
			"💎",
			1000,
			"$9.99 value",
			"rare",
			0,
			2,
		],
		[
			"1,700 Robux",
			"Big spender! Enough for most limiteds & UGC",
			"robux",
			"👑",
			2000,
			"$19.99 value",
			"epic",
			0,
			3,
		],
		[
			"4,500 Robux",
			"MEGA pack for serious collectors",
			"robux",
			"🏆",
			5000,
			"$49.99 value",
			"legendary",
			0,
			4,
		],

		// Gaming Time
		[
			"30 Min Extra Gaming",
			"Add 30 minutes to your daily screen time",
			"gaming",
			"🎮",
			50,
			null,
			"common",
			0,
			5,
		],
		[
			"1 Hour Extra Gaming",
			"Full extra hour of gaming goodness",
			"gaming",
			"🕹️",
			90,
			null,
			"common",
			0,
			6,
		],
		[
			"Gaming Marathon",
			"Unlimited gaming for one weekend day!",
			"gaming",
			"🔥",
			400,
			null,
			"rare",
			0,
			7,
		],
		[
			"Stay Up Late Pass",
			"Extend bedtime by 1 hour (Fri/Sat only)",
			"gaming",
			"🌙",
			300,
			null,
			"rare",
			1,
			8,
		],

		// LEGO
		[
			"Small LEGO Set",
			"150-200 pieces • Speed Champions, small Star Wars, Creator 3-in-1",
			"lego",
			"🧱",
			800,
			"$15-20 value",
			"rare",
			0,
			9,
		],
		[
			"Medium LEGO Set",
			"300-500 pieces • Ninjago dragons, City sets, Technic vehicles",
			"lego",
			"🏗️",
			1500,
			"$30-50 value",
			"epic",
			0,
			10,
		],
		[
			"Large LEGO Set",
			"750-1,000 pieces • Big Star Wars ships, detailed Technic, Ideas sets",
			"lego",
			"🏰",
			3000,
			"$75-100 value",
			"legendary",
			0,
			11,
		],
		[
			"Ultimate LEGO Set",
			"1,500+ pieces • UCS Star Wars, Hogwarts, massive Technic builds",
			"lego",
			"🌟",
			6000,
			"$150+ value",
			"legendary",
			0,
			12,
		],

		// Experiences
		[
			"Pick Dinner Tonight",
			"You decide what the family eats tonight!",
			"experience",
			"🍕",
			150,
			null,
			"common",
			0,
			13,
		],
		[
			"Movie Night (Your Pick)",
			"Choose the movie + snacks for family movie night",
			"experience",
			"🎬",
			200,
			null,
			"common",
			0,
			14,
		],
		[
			"Skip One Chore",
			"One-time pass to skip a single assigned chore",
			"experience",
			"🎟️",
			100,
			null,
			"common",
			1,
			15,
		],
		[
			"Friend Sleepover",
			"Invite a friend over for gaming & sleepover",
			"experience",
			"🎉",
			500,
			null,
			"rare",
			0,
			16,
		],
		[
			"Restaurant of Choice",
			"Family goes to YOUR favorite restaurant",
			"experience",
			"🍔",
			750,
			null,
			"epic",
			0,
			17,
		],
		[
			"Special Day Out",
			"Arcade, mini golf, laser tag, or your choice activity!",
			"experience",
			"🎢",
			1200,
			null,
			"epic",
			0,
			18,
		],
	];

	rewards.forEach((r) => rewardStmt.run(...r));
	console.log("✅ Rewards created");
}
