import datetime
import json
import subprocess
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import RGBColor
from vibe_justice.utils.paths import get_data_directory


def open_in_explorer(file_path: str):
    """
    Opens Windows Explorer with the file selected.
    Uses list-form args (shell=False) to prevent command injection.
    """
    clean_path = str(file_path).replace("/", "\\")
    subprocess.Popen(["explorer", f"/select,{clean_path}"], shell=False)


def generate_case_export(case_id: str, data: dict, format: str = "docx") -> str:
    """
    Generates a case export file in the specified format.
    Returns the absolute path to the generated file.
    """
    export_dir = Path(get_data_directory()) / "exports"
    export_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d_%H%M%S")

    if format.lower() == "docx":
        filename = f"{case_id}_summary_{timestamp}.docx"
        file_path = export_dir / filename
        _generate_docx(case_id, data, file_path)
    elif format.lower() == "md":
        filename = f"{case_id}_summary_{timestamp}.md"
        file_path = export_dir / filename
        _generate_markdown(case_id, data, file_path)
    elif format.lower() == "txt":
        filename = f"{case_id}_summary_{timestamp}.txt"
        file_path = export_dir / filename
        _generate_text(case_id, data, file_path)
    else:
        raise ValueError(f"Unsupported format: {format}")

    return str(file_path)


def _generate_docx(case_id: str, data: dict, file_path: Path):
    doc = Document()

    # Title
    title = doc.add_heading(f"CASE REPORT: {case_id}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    doc.add_heading("Case Information", level=1)
    p = doc.add_paragraph()
    p.add_run(f"Status: ").bold = True
    p.add_run(f"{data.get('status', 'Unknown')}\n")
    p.add_run(f"Jurisdiction: ").bold = True
    p.add_run(f"{data.get('jurisdiction', 'N/A')}\n")
    p.add_run(f"Created: ").bold = True
    p.add_run(f"{data.get('created_at', 'N/A')}\n")

    if data.get("is_archived"):
        run = p.add_run(f"\n[ARCHIVED on {data.get('archived_at', 'Unknown')}]")
        run.font.color.rgb = RGBColor(255, 0, 0)

    # Goals
    doc.add_heading("Research Goals", level=1)
    doc.add_paragraph(data.get("research_goals", "No specific goals listed."))

    # Footer
    section = doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = f"Generated by Vibe Justice | Confidentality Level: HIGH"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    doc.save(file_path)


def _generate_markdown(case_id: str, data: dict, file_path: Path):
    content = f"# CASE REPORT: {case_id}\n\n"
    content += "## Case Information\n"
    content += f"- **Status**: {data.get('status', 'Unknown')}\n"
    content += f"- **Jurisdiction**: {data.get('jurisdiction', 'N/A')}\n"
    content += f"- **Created**: {data.get('created_at', 'N/A')}\n"

    if data.get("is_archived"):
        content += f"- **ARCHIVED**: {data.get('archived_at', 'Unknown')}\n"

    content += "\n## Research Goals\n"
    content += f"{data.get('research_goals', 'No specific goals listed.')}\n"

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)


def _generate_text(case_id: str, data: dict, file_path: Path):
    content = f"CASE REPORT: {case_id}\n"
    content += "=" * 30 + "\n\n"
    content += "CASE INFORMATION\n"
    content += f"Status:       {data.get('status', 'Unknown')}\n"
    content += f"Jurisdiction: {data.get('jurisdiction', 'N/A')}\n"
    content += f"Created:      {data.get('created_at', 'N/A')}\n"

    if data.get("is_archived"):
        content += f"[ARCHIVED]    {data.get('archived_at', 'Unknown')}\n"

    content += "\nRESEARCH GOALS\n"
    content += f"{data.get('research_goals', 'No specific goals listed.')}\n"

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
