# cleanup-vcs-duplicates.ps1
# Purpose: Remove duplicate/stale directories from vibe-code-studio
# Safety: Creates backup before deletion
# Author: Claude Architect
# Date: 2026-01-25

param(
    [switch]$DryRun = $false,
    [switch]$SkipBackup = $false
)

$ErrorActionPreference = "Stop"
$VCSPath = "C:\dev\apps\vibe-code-studio"
$BackupDir = "C:\dev\apps\vibe-code-studio\_backups"
$Timestamp = Get-Date -Format "yyyyMMdd_HHmmss"

Write-Host "=== VCS Cleanup Script ===" -ForegroundColor Cyan
Write-Host "Mode: $(if($DryRun){'DRY RUN'}else{'LIVE'})" -ForegroundColor $(if($DryRun){'Yellow'}else{'Red'})

# Directories to remove (duplicates/build artifacts)
$ToDelete = @(
    "$VCSPath\.deploy-test"      # Full duplicate with nested node_modules
    "$VCSPath\coverage"          # Regenerated by tests
    "$VCSPath\test-results"      # Regenerated by tests
    "$VCSPath\test_screenshots"  # Debug artifacts
)

# Calculate space before
$SpaceBefore = 0
foreach ($dir in $ToDelete) {
    if (Test-Path $dir) {
        $size = (Get-ChildItem $dir -Recurse -File -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
        $sizeMB = [math]::Round($size / 1MB, 2)
        Write-Host "  Found: $dir ($sizeMB MB)" -ForegroundColor Yellow
        $SpaceBefore += $size
    }
}

Write-Host "`nTotal to free: $([math]::Round($SpaceBefore / 1GB, 2)) GB" -ForegroundColor Green

if ($DryRun) {
    Write-Host "`n[DRY RUN] No files deleted. Run without -DryRun to execute." -ForegroundColor Yellow
    exit 0
}

# Backup critical src before any deletion
if (-not $SkipBackup) {
    Write-Host "`nCreating backup..." -ForegroundColor Cyan
    if (-not (Test-Path $BackupDir)) { New-Item -ItemType Directory -Path $BackupDir -Force | Out-Null }
    
    $BackupPath = "$BackupDir\src_backup_$Timestamp.zip"
    Compress-Archive -Path "$VCSPath\src" -DestinationPath $BackupPath -Force
    Write-Host "  Backup created: $BackupPath" -ForegroundColor Green
}

# Delete directories
foreach ($dir in $ToDelete) {
    if (Test-Path $dir) {
        Write-Host "Removing: $dir" -ForegroundColor Red
        Remove-Item -Path $dir -Recurse -Force -ErrorAction Continue
    }
}

# Clean stale files in root
$StalePatterns = @("*.log", "nul", "*.tsbuildinfo")
foreach ($pattern in $StalePatterns) {
    Get-ChildItem -Path $VCSPath -Filter $pattern -File -ErrorAction SilentlyContinue | ForEach-Object {
        Write-Host "Removing stale file: $($_.Name)" -ForegroundColor DarkYellow
        Remove-Item $_.FullName -Force
    }
}

Write-Host "`n=== Cleanup Complete ===" -ForegroundColor Green
Write-Host "Run 'pnpm nx reset' to clear Nx cache if needed." -ForegroundColor Cyan
