import React, { useState } from 'react';
import type { Reward, RewardRequest } from '../../types';
import { PlusIcon } from '../ui/icons/PlusIcon';

type Action = 'approve' | 'deny' | 'fulfill' | 'retry_debit' | 'retry_refund';
interface Props { rewards: Reward[]; onUpdateRewards: (action: React.SetStateAction<Reward[]>) => Promise<boolean>; claimedRewards: RewardRequest[]; onApproval: (id: string, action: Action) => Promise<boolean>; rewardError: string | null; rewardBlocked?: boolean; }
const generateId = () => { if (!globalThis.crypto || typeof globalThis.crypto.randomUUID !== 'function') throw new Error('Secure catalog IDs are unavailable on this device.'); return `reward_${globalThis.crypto.randomUUID()}`; };
const statusText: Record<RewardRequest['status'], string> = { debit_pending: 'Debit pending — retry required', pending_approval: 'Pending approval', approved: 'Approved — awaiting fulfillment', refund_pending: 'Refund pending — retry required', denied: 'Denied and refunded', fulfilled: 'Fulfilled' };

const RewardSettings = ({ rewards, onUpdateRewards, claimedRewards, onApproval, rewardError, rewardBlocked = false }: Props) => {
  const [newName, setNewName] = useState(''); const [newCost, setNewCost] = useState(''); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const blocked = rewardBlocked;
  const act = async (id: string, action: Action) => { setBusy(`${id}:${action}`); setError(null); try { const ok = await onApproval(id, action); if (!ok) setError('The request could not be updated. Its saved status is still shown below.'); } catch { setError('The request could not be updated.'); } finally { setBusy(null); } };
  const add = async (event: React.FormEvent) => { event.preventDefault(); const cost = Number(newCost); if (blocked || !newName.trim() || !Number.isSafeInteger(cost) || cost <= 0) { setError(blocked ? 'Reward actions are blocked until stored records are reviewed.' : 'Enter a reward name and a whole-number token cost.'); return; } setError(null); let id: string; try { id = generateId(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Secure catalog IDs are unavailable.'); return; } try { if (await onUpdateRewards((prev) => [...prev, { id, name: newName.trim(), cost }])) { setNewName(''); setNewCost(''); } else setError('The reward catalog was not saved.'); } catch { setError('The reward catalog was not saved.'); } };
  return <div className="p-6 bg-background-surface border border-[var(--border-color)] rounded-2xl">
    <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[var(--primary-accent)] to-[var(--secondary-accent)] mb-4">Reward System</h3>
    {(error || rewardError) && <p role="alert" className="mb-3 text-sm text-red-300">{error ?? rewardError}</p>}
    <form onSubmit={add} className="mb-8 p-4 bg-slate-800/50 rounded-lg"><h4 className="font-semibold text-lg mb-3">Create a New Reward</h4><div className="flex flex-col md:flex-row gap-4"><input disabled={blocked} aria-label="Reward name" type="text" placeholder="Reward Name (e.g., Pizza Night)" value={newName} onChange={(e) => setNewName(e.target.value)} className="flex-grow p-3 bg-slate-700/50 border border-slate-600 rounded-lg"/><input disabled={blocked} aria-label="Reward cost" type="number" placeholder="Point Cost" value={newCost} onChange={(e) => setNewCost(e.target.value)} className="w-full md:w-32 p-3 bg-slate-700/50 border border-slate-600 rounded-lg"/><button disabled={blocked} type="submit" className="flex items-center justify-center gap-2 px-5 py-3 font-semibold text-background-main bg-[var(--primary-accent)] rounded-lg"><PlusIcon className="w-5 h-5"/> Add</button></div></form>
    {claimedRewards.length > 0 && <div className="mb-8"><h4 className="font-semibold text-lg mb-3 text-yellow-400">Reward Requests</h4><div className="space-y-3">{claimedRewards.map((request) => { const disabled = blocked || (busy?.startsWith(`${request.requestId}:`) ?? false); return <div key={request.requestId} className="p-4 bg-slate-800/50 rounded-lg"><p className="font-bold">{request.reward.name}</p><p className="text-sm text-slate-400">{request.reward.cost} Tokens · {statusText[request.status]}</p><div className="flex gap-3 mt-3">{request.status === 'pending_approval' && <><button disabled={disabled} onClick={() => void act(request.requestId, 'deny')} className="px-4 py-2 font-semibold text-white bg-red-600 rounded-lg disabled:opacity-50">Deny</button><button disabled={disabled} onClick={() => void act(request.requestId, 'approve')} className="px-4 py-2 font-semibold text-white bg-violet-600 rounded-lg disabled:opacity-50">Approve</button></>}{request.status === 'approved' && <><button disabled={disabled} onClick={() => void act(request.requestId, 'deny')} className="px-4 py-2 font-semibold text-white bg-red-600 rounded-lg disabled:opacity-50">Deny</button><button disabled={disabled} onClick={() => void act(request.requestId, 'fulfill')} className="px-4 py-2 font-semibold text-white bg-violet-600 rounded-lg disabled:opacity-50">Mark fulfilled</button></>}{request.status === 'debit_pending' && <button disabled={disabled} onClick={() => void act(request.requestId, 'retry_debit')} className="px-4 py-2 font-semibold text-white bg-violet-600 rounded-lg disabled:opacity-50">Retry debit</button>}{request.status === 'refund_pending' && <button disabled={disabled} onClick={() => void act(request.requestId, 'retry_refund')} className="px-4 py-2 font-semibold text-white bg-violet-600 rounded-lg disabled:opacity-50">Retry refund</button>}</div></div>; })}</div></div>}
    <div><h4 className="font-semibold text-lg mb-3">Manage Rewards</h4>{rewards.map((reward) => <div key={reward.id} className="p-4 bg-slate-800/50 rounded-lg flex items-center justify-between"><div><p className="font-bold">{reward.name}</p><p className="text-sm text-slate-400">{reward.cost} Tokens</p></div><button disabled={blocked} onClick={() => void onUpdateRewards((prev) => prev.filter((item) => item.id !== reward.id))} className="px-4 py-2 font-semibold text-slate-300 bg-slate-700 rounded-lg disabled:opacity-50">Delete</button></div>)}</div>
  </div>;
};
export default RewardSettings;
