import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  LandingPage,
  createDefaultLandingContent,
} from '@vibetech/landing';

const content = createDefaultLandingContent({
  productName: 'FactoryRuntimeSmoke',
  badge: 'Generated by @vibetech/factory:saas',
  title: 'FactoryRuntimeSmoke',
  subtitle:
    'This scaffold includes a React frontend, a Fastify API, and a first entitlement-aware API surface.',
  previewItems: [
    'Shared landing page',
    'Fastify API',
    'Protected pro route',
    'Workspace package wiring',
  ],
  featuresHeading: 'Factory defaults for monetized apps',
  featuresSubheading:
    'The generator starts with shared landing content, auth and entitlement package dependencies, and a first sign-in protected backend route.',
  features: [
    {
      title: 'Landing package',
      description: 'The frontend starts on the shared landing system instead of placeholder copy.',
    },
    {
      title: 'Login flow',
      description:
        'The generated app now includes a starter operator sign-in flow backed by @vibetech/auth.',
    },
    {
      title: 'Entitlement seam',
      description: 'The generated API includes a first plan-gated route under /api/pro.',
    },
  ],
  ctaHeading: 'Start from shared monetization primitives',
  ctaBody:
    'Replace the copy and plan details, then move straight into product-specific workflow work.',
  footerRight: 'Built with the VibeTech factory SaaS generator',
});

interface GeneratedAuthUser {
  email: string;
  fullName?: string;
}

export function App() {
  const pathname = window.location.pathname;
  const [authConfigured, setAuthConfigured] = useState(false);
  const [userEmail, setUserEmail] = useState('');
  const [password, setPassword] = useState('');
  const [currentUser, setCurrentUser] = useState<GeneratedAuthUser | null>(null);
  const [authMessage, setAuthMessage] = useState<string | null>(null);
  const [proMessage, setProMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState<'auth' | 'pro' | null>(null);
  const apiBase = useMemo(() => import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:5320', []);

  const refreshSession = useCallback(async () => {
    try {
      const response = await fetch(`${apiBase}/api/auth/me`, {
        credentials: 'include',
      });
      const body = (await response.json()) as {
        configured?: boolean;
        user?: GeneratedAuthUser | null;
      };

      setAuthConfigured(Boolean(body.configured));
      setCurrentUser(body.user ?? null);
    } catch {
      setAuthConfigured(false);
      setCurrentUser(null);
    }
  }, [apiBase]);

  useEffect(() => {
    void refreshSession();
  }, [refreshSession]);

  async function signIn() {
    setLoading('auth');
    setAuthMessage(null);

    try {
      const response = await fetch(`${apiBase}/api/auth/login`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          email: userEmail,
          password,
        }),
      });
      const body = (await response.json()) as {
        user?: GeneratedAuthUser;
        error?: string;
        detail?: string;
      };

      if (!response.ok || !body.user) {
        throw new Error(body.detail ?? body.error ?? 'Unable to sign in');
      }

      setCurrentUser(body.user);
      setAuthConfigured(true);
      setPassword('');
    } catch (requestError) {
      setAuthMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function signOut() {
    setLoading('auth');
    setAuthMessage(null);

    try {
      await fetch(`${apiBase}/api/auth/logout`, {
        method: 'POST',
        credentials: 'include',
      });
      setCurrentUser(null);
      await refreshSession();
    } catch (requestError) {
      setAuthMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  async function checkProRoute() {
    setLoading('pro');
    setProMessage(null);

    try {
      const response = await fetch(`${apiBase}/api/pro`, {
        credentials: 'include',
        headers: {
          'x-plan': 'pro',
        },
      });
      const body = (await response.json()) as {
        error?: string;
        feature?: string;
        plan?: string;
      };

      if (!response.ok || !body.feature) {
        throw new Error(body.error ?? 'Protected route check failed');
      }

      setProMessage(`Protected route is live for the ${body.plan} plan: ${body.feature}.`);
    } catch (requestError) {
      setProMessage(requestError instanceof Error ? requestError.message : String(requestError));
    } finally {
      setLoading(null);
    }
  }

  if (pathname === '/terms') {
    return (
      <LegalPage
        title="Terms of service"
        intro="This generated SaaS app includes starter legal copy so every factory app has real terms and privacy entry points on day one."
        sections={[
          {
            heading: 'Use of the service',
            body: 'Use the generated app for the workflow it is configured to support. Product-specific commitments still belong to the app owner.',
          },
          {
            heading: 'Billing',
            body: 'Paid access is expected to flow through the shared Stripe billing package and the plans configured for this product.',
          },
          {
            heading: 'Acceptable use',
            body: 'Do not upload or submit content you are not allowed to process. Replace this section with product-specific rules before shipping.',
          },
        ]}
      />
    );
  }

  if (pathname === '/privacy') {
    return (
      <LegalPage
        title="Privacy policy"
        intro="This generated SaaS app includes starter privacy copy so every factory app has legal-friendly structure on day one."
        sections={[
          {
            heading: 'Data collection',
            body: 'The generated app may store account, billing, and workflow data required to deliver the product. Replace this with the actual data inventory before production.',
          },
          {
            heading: 'Payments',
            body: 'Payments should be delegated to Stripe through the shared billing package. Raw card data should not be stored by the app.',
          },
          {
            heading: 'Analytics',
            body: 'Analytics are scaffolded through the shared analytics package and should stay limited to the events needed to operate the product.',
          },
        ]}
      />
    );
  }

  return (
    <main>
      <LandingPage content={content} />
      <section className="page auth-grid">
        <article className="grid-card">
          <div className="eyebrow">Generated auth</div>
          <h2>
            {currentUser
              ? 'Signed in'
              : authConfigured
                ? 'Sign in required'
                : 'Auth not configured'}
          </h2>
          <p>
            {currentUser
              ? `Session active for ${currentUser.fullName ?? currentUser.email}.`
              : authConfigured
                ? 'Use the generated operator account to unlock the first pro route.'
                : 'Set AUTH_SECRET and the DEMO_USER_* values in .env before using the starter login flow.'}
          </p>
          {authMessage ? <p className="message">{authMessage}</p> : null}
        </article>
        <article className="grid-card auth-form-card">
          <div className="eyebrow">Operator account</div>
          {currentUser ? (
            <button
              className="secondary-button"
              onClick={() => void signOut()}
              disabled={loading !== null}
            >
              {loading === 'auth' ? 'Signing out...' : 'Sign out'}
            </button>
          ) : (
            <>
              <label className="field">
                Email
                <input
                  type="email"
                  value={userEmail}
                  onChange={(event) => setUserEmail(event.target.value)}
                  placeholder="owner@example.com"
                />
              </label>
              <label className="field">
                Password
                <input
                  type="password"
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                  placeholder="change-this-password"
                />
              </label>
              <button onClick={() => void signIn()} disabled={loading !== null}>
                {loading === 'auth' ? 'Signing in...' : 'Sign in for pro access'}
              </button>
            </>
          )}
        </article>
        <article className="grid-card">
          <div className="eyebrow">Pro route</div>
          <h2>/api/pro</h2>
          <p>
            The factory SaaS scaffold now includes a starter login flow and a sign-in protected
            entitlement route.
          </p>
          <button
            className="secondary-button"
            onClick={() => void checkProRoute()}
            disabled={loading !== null}
          >
            {loading === 'pro' ? 'Checking route...' : 'Check protected pro route'}
          </button>
          {proMessage ? <p className="message">{proMessage}</p> : null}
        </article>
      </section>
      <section style={{ padding: '0 24px 48px' }}>
        <div
          style={{
            maxWidth: '1120px',
            margin: '0 auto',
            display: 'flex',
            justifyContent: 'space-between',
            gap: '12px',
            flexWrap: 'wrap',
            color: '#94a3b8',
          }}
        >
          <span>Factory SaaS apps ship with legal stubs at /terms and /privacy.</span>
          <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
            <a href="/terms" style={{ color: '#67e8f9' }}>
              Terms
            </a>
            <a href="/privacy" style={{ color: '#67e8f9' }}>
              Privacy
            </a>
          </div>
        </div>
      </section>
    </main>
  );
}

function LegalPage({
  title,
  intro,
  sections,
}: {
  title: string;
  intro: string;
  sections: Array<{ heading: string; body: string }>;
}) {
  return (
    <main
      style={{
        minHeight: '100vh',
        padding: '48px 24px',
        background: '#08111f',
        color: '#f5f7fb',
        fontFamily: 'Inter, system-ui, sans-serif',
      }}
    >
      <div
        style={{
          maxWidth: '880px',
          margin: '0 auto',
          border: '1px solid rgba(148, 163, 184, 0.2)',
          borderRadius: '8px',
          background: 'rgba(15, 23, 42, 0.82)',
          padding: '24px',
        }}
      >
        <div
          style={{
            display: 'inline-block',
            marginBottom: '16px',
            padding: '6px 12px',
            borderRadius: '999px',
            background: 'rgba(14, 165, 233, 0.16)',
            color: '#67e8f9',
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '0.08em',
          }}
        >
          Factory legal stub
        </div>
        <h1 style={{ margin: '0 0 16px', fontSize: '40px', lineHeight: 1.1 }}>{title}</h1>
        <p style={{ margin: '0 0 24px', color: '#b7c3d6', lineHeight: 1.7 }}>{intro}</p>
        <div style={{ display: 'grid', gap: '20px' }}>
          {sections.map((section) => (
            <section key={section.heading}>
              <h2 style={{ margin: '0 0 8px', fontSize: '22px' }}>{section.heading}</h2>
              <p style={{ margin: 0, color: '#dbe4f2', lineHeight: 1.7 }}>{section.body}</p>
            </section>
          ))}
        </div>
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', marginTop: '24px' }}>
          <a href="/" style={{ color: '#67e8f9' }}>
            Back to app
          </a>
          <a href="/terms" style={{ color: '#67e8f9' }}>
            Terms
          </a>
          <a href="/privacy" style={{ color: '#67e8f9' }}>
            Privacy
          </a>
        </div>
      </div>
    </main>
  );
}
