/**
 * PlanMarkdownBuilder — pure formatting for spec 05 Plan Mode Phase 1.
 * Converts a TaskPlanner response (+ confidence insights) into the structured
 * markdown plan written to <workspaceRoot>/.vcs/plans/ and recorded as a
 * spec-09 plan artifact. No I/O here.
 * Spec: FEATURE_SPECS/competitive-gaps/05-PLAN-MODE.md
 */
import type { PlanningInsights, TaskPlanResponse } from '../../../types';

export interface PlanStepLine {
  order: number;
  title: string;
  description: string;
  actionType: string;
  /** File/dir the step targets when the action params carry one. */
  target?: string;
}

export interface PlanMarkdownInput {
  title: string;
  userRequest: string;
  reasoning: string;
  steps: PlanStepLine[];
  warnings: string[];
  insights?: PlanningInsights;
  workspaceRoot: string;
  currentFile?: string;
  hasAgentStandards: boolean;
  createdAtIso: string;
}

export const PLANS_DIR_SEGMENT = '.vcs/plans';
const SLUG_MAX_LENGTH = 60;

/** Kebab-case slug for plan file names ('plan' when nothing survives). */
export function slugify(text: string): string {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, SLUG_MAX_LENGTH)
    .replace(/-+$/g, '');
  return slug || 'plan';
}

/** Local YYYYMMDD-HHMMSS stamp used in plan file names. */
export function formatPlanTimestamp(date: Date): string {
  const pad = (value: number): string => String(value).padStart(2, '0');
  const day = `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`;
  const time = `${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
  return `${day}-${time}`;
}

/** `<slug>-<timestamp>.md` file name for a plan. */
export function buildPlanFileName(title: string, createdAt: Date): string {
  return `${slugify(title)}-${formatPlanTimestamp(createdAt)}.md`;
}

/** Extracts the file-ish target from a step's action params, if any. */
function stepTarget(params: Record<string, unknown> | undefined): string | undefined {
  if (!params) {
    return undefined;
  }
  const candidate = params['filePath'] ?? params['path'] ?? params['workingDirectory'];
  return typeof candidate === 'string' && candidate ? candidate : undefined;
}

/** Adapter: TaskPlanner output → builder input. */
export function fromTaskPlanResponse(
  userRequest: string,
  response: TaskPlanResponse,
  meta: {
    workspaceRoot: string;
    currentFile?: string;
    hasAgentStandards: boolean;
    createdAt: Date;
    insights?: PlanningInsights;
  }
): PlanMarkdownInput {
  return {
    title: response.task.title || userRequest.slice(0, 80),
    userRequest,
    reasoning: response.reasoning,
    steps: response.task.steps.map((step, index) => ({
      order: index + 1,
      title: step.title,
      description: step.description,
      actionType: step.action?.type ?? 'unknown',
      target: stepTarget(step.action?.params as Record<string, unknown> | undefined),
    })),
    warnings: response.warnings ?? [],
    insights: meta.insights,
    workspaceRoot: meta.workspaceRoot,
    currentFile: meta.currentFile,
    hasAgentStandards: meta.hasAgentStandards,
    createdAtIso: meta.createdAt.toISOString(),
  };
}

function buildStepsSection(steps: PlanStepLine[]): string {
  if (steps.length === 0) {
    return '_No steps were generated._';
  }
  return steps
    .map(step => {
      const target = step.target ? ` (\`${step.target}\`)` : '';
      const detail = step.description ? `\n  ${step.description}` : '';
      return `- [ ] ${step.order}. ${step.title} — \`${step.actionType}\`${target}${detail}`;
    })
    .join('\n');
}

function buildConfidenceSection(insights: PlanningInsights): string {
  const percent = (value: number): string => `${Math.round(value * 100)}%`;
  return [
    `- Overall confidence: ${percent(insights.overallConfidence)}`,
    `- High-risk steps: ${insights.highRiskSteps}`,
    `- Memory-backed steps: ${insights.memoryBackedSteps}`,
    `- Estimated success rate: ${percent(insights.estimatedSuccessRate)}`,
  ].join('\n');
}

/** Render the full plan markdown document. */
export function buildPlanMarkdown(input: PlanMarkdownInput): string {
  const sections = [
    `# ${input.title}`,
    `> Generated by Plan Mode on ${input.createdAtIso} · workspace: ${input.workspaceRoot}`,
    `## Goal\n\n${input.userRequest.trim()}`,
  ];
  if (input.reasoning.trim()) {
    sections.push(`## Reasoning\n\n${input.reasoning.trim()}`);
  }
  sections.push(`## Steps\n\n${buildStepsSection(input.steps)}`);
  if (input.warnings.length > 0) {
    sections.push(`## Warnings\n\n${input.warnings.map(w => `- ${w}`).join('\n')}`);
  }
  if (input.insights) {
    sections.push(`## Confidence\n\n${buildConfidenceSection(input.insights)}`);
  }
  sections.push(
    `## Context\n\n${[
      `- Current file: ${input.currentFile ?? 'none'}`,
      `- AGENTS.md standards applied: ${input.hasAgentStandards ? 'yes' : 'no'}`,
    ].join('\n')}`
  );
  return `${sections.join('\n\n')}\n`;
}
