[mypy]
python_version = 3.13
mypy_path = src
explicit_package_bases = True
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = True
files =
    src/config.py,
    src/database.py,
    src/kraken_client.py,
    src/strategies.py,
    src/trading_engine.py,
    src/websocket_manager.py,
    scripts/start_live_trading.py
